// lib/words_06_10.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_06_10: Word[] = [
  { kanji: "立つ", hiragana: "たつ", meaning: "서다, 일어서다" },
  { kanji: "先", hiragana: "さき", meaning: "앞, 선두, 전방, 먼저" },
  { kanji: "スプーン", hiragana: "", meaning: "스푼, 숟가락" },
  { kanji: "毎晩", hiragana: "まいばん", meaning: "매일 밤" },
  { kanji: "沢山", hiragana: "たくさん", meaning: "많음, 충분함" },
  { kanji: "近い", hiragana: "ちかい", meaning: "가깝다" },
  { kanji: "静か", hiragana: "しずか", meaning: "조용함" },
  { kanji: "新聞", hiragana: "しんぶん", meaning: "신문" },
  { kanji: "本", hiragana: "ほん", meaning: "책" },
  { kanji: "いくら", hiragana: "", meaning: "얼마, 어느 정도, 아무리" },
  { kanji: "持つ", hiragana: "もつ", meaning: "지니다, 쥐다, 들다, 가지다" },
  { kanji: "買う", hiragana: "かう", meaning: "사다, 구입하다" },
  { kanji: "秋", hiragana: "あき", meaning: "가을" },
  { kanji: "靴下", hiragana: "くつした", meaning: "양말" },
  { kanji: "お茶", hiragana: "おちゃ", meaning: "차" },
  { kanji: "どんな", hiragana: "", meaning: "어떤, 어떠한" },
  { kanji: "水", hiragana: "みず", meaning: "물" },
  { kanji: "ナイフ", hiragana: "", meaning: "나이프, 칼" },
  { kanji: "顔", hiragana: "かお", meaning: "얼굴" },
  { kanji: "昨日", hiragana: "きのう", meaning: "어제" },
  { kanji: "切符", hiragana: "きっぷ", meaning: "티켓, 표" },
  { kanji: "昼ご飯", hiragana: "ひるごはん", meaning: "점심 식사, 점심밥" },
  { kanji: "休み", hiragana: "やすみ", meaning: "휴식, 휴일, 휴가, 방학" },
  { kanji: "色々", hiragana: "いろいろ", meaning: "여러가지, 다양한, 가지각색" },
  { kanji: "銀行", hiragana: "ぎんこう", meaning: "은행" },
  { kanji: "門", hiragana: "もん", meaning: "문, 대문" },
  { kanji: "留学生", hiragana: "りゅうがくせい", meaning: "유학생" },
  { kanji: "丈夫", hiragana: "じょうぶ", meaning: "건강함, 튼튼함" },
  { kanji: "川", hiragana: "かわ", meaning: "강" },
  { kanji: "年", hiragana: "とし", meaning: "년, 해" },
  { kanji: "住む", hiragana: "すむ", meaning: "살다, 거주하다" },
  { kanji: "狭い", hiragana: "せまい", meaning: "좁다" },
  { kanji: "飲む", hiragana: "のむ", meaning: "마시다, 복용하다" },
  { kanji: "一つ", hiragana: "ひとつ", meaning: "하나, 한 개" },
  { kanji: "上がる", hiragana: "あがる", meaning: "오르다, 올라가다" },
  { kanji: "一日", hiragana: "いちにち", meaning: "일일, 하루" },
  { kanji: "七", hiragana: "しち", meaning: "7" },
  { kanji: "一番", hiragana: "いちばん", meaning: "가장, 제일, 첫째, 첫번" },
  { kanji: "山", hiragana: "やま", meaning: "산" },
  { kanji: "十", hiragana: "じゅう", meaning: "10" },
  { kanji: "降る", hiragana: "ふる", meaning: "내리다, 오다,(비,눈 등이 내리다)" },
  { kanji: "売る", hiragana: "うる", meaning: "팔다, 판매하다" },
  { kanji: "何", hiragana: "なに", meaning: "무엇, 뭐" },
  { kanji: "果物", hiragana: "くだもの", meaning: "과일" },
  { kanji: "問題", hiragana: "もんだい", meaning: "문제" },
  { kanji: "建物", hiragana: "たてもの", meaning: "건물" },
  { kanji: "手紙", hiragana: "てがみ", meaning: "편지" },
  { kanji: "毎週", hiragana: "まいしゅう", meaning: "매주" },
  { kanji: "ありがとうございます", hiragana: "", meaning: "감사합니다" },
  { kanji: "上着", hiragana: "うわぎ", meaning: "상의, 겉옷" },
  { kanji: "痛い", hiragana: "いたい", meaning: "아프다" },
  { kanji: "弟", hiragana: "おとうと", meaning: "남동생" },
  { kanji: "二日", hiragana: "ふつか", meaning: "이틀, 2일" },
  { kanji: "車", hiragana: "くるま", meaning: "차, 자동차" },
  { kanji: "子供", hiragana: "こども", meaning: "아이, 어린이, 자식" },
  { kanji: "野菜", hiragana: "やさい", meaning: "야채, 채소" },
  { kanji: "上", hiragana: "うえ", meaning: "위, 위쪽" },
  { kanji: "良い", hiragana: "よい, いい", meaning: "좋다, ~하기 좋다" },
  { kanji: "分かる", hiragana: "わかる", meaning: "알다, 이해하다" },
  { kanji: "汚い", hiragana: "きたない", meaning: "더럽다, 불결하다" },
  { kanji: "習う", hiragana: "ならう", meaning: "배우다, 익히다" },
  { kanji: "終わる", hiragana: "おわる", meaning: "끝나다, 마치다" },
  { kanji: "重い", hiragana: "おもい", meaning: "무겁다" },
  { kanji: "夕方", hiragana: "ゆうがた", meaning: "저녁때, 해질녁" },
  { kanji: "所", hiragana: "ところ", meaning: "곳, 장소" },
  { kanji: "緑", hiragana: "みどり", meaning: "녹색" },
  { kanji: "宿題", hiragana: "しゅくだい", meaning: "숙제" },
  { kanji: "借りる", hiragana: "かりる", meaning: "빌리다" },
  { kanji: "広い", hiragana: "ひろい", meaning: "넓다" },
  { kanji: "消す", hiragana: "けす", meaning: "지우다, 끄다, 없애다" },
  { kanji: "余り", hiragana: "あまり", meaning: "별로, 그다지, 지나치게, 여분" },
  { kanji: "時間", hiragana: "じかん", meaning: "시간" },
  { kanji: "病気", hiragana: "びょうき", meaning: "병, 질병" },
  { kanji: "消える", hiragana: "きえる", meaning: "꺼지다, 사라지다, 없어지다" },
  { kanji: "死ぬ", hiragana: "しぬ", meaning: "죽다" },
  { kanji: "教壇", hiragana: "きょうだん", meaning: "교단, 교직" },
  { kanji: "海", hiragana: "うみ", meaning: "바다" },
  { kanji: "議題", hiragana: "ぎだい", meaning: "의제" },
  { kanji: "届く", hiragana: "とどく", meaning: "닿다, 도달하다, 미치다, 이르다" },
  { kanji: "距離", hiragana: "きょり", meaning: "거리, 간격" },
  { kanji: "荷物", hiragana: "にもつ", meaning: "짐, 화물" },
  { kanji: "株", hiragana: "かぶ", meaning: "주식, 그루, 포기" },
  { kanji: "台風", hiragana: "たいふう", meaning: "태풍" },
  { kanji: "多く", hiragana: "おおく", meaning: "많음, 대개" },
  { kanji: "ずり下がる", hiragana: "ずりさがる", meaning: "흘러내리다" },
  { kanji: "一杯", hiragana: "いっぱい", meaning: "한 잔, 한 그릇" },
  { kanji: "起こる", hiragana: "おこる", meaning: "발생하다, 생기다, 일어나다" },
  { kanji: "人", hiragana: "ひと", meaning: "사람" },
  { kanji: "覚悟", hiragana: "かくご", meaning: "각오" },
  { kanji: "行き合う", hiragana: "ゆきあう", meaning: "마주치다, 가다가 만나다" },
  { kanji: "薄める", hiragana: "うすめる", meaning: "묽게 하다, 옅게 하다" },
  { kanji: "機会", hiragana: "きかい", meaning: "기회" },
  { kanji: "親", hiragana: "おや", meaning: "어버이, 부모" },
  { kanji: "財布", hiragana: "さいふ", meaning: "지갑" },
  { kanji: "前", hiragana: "まえ", meaning: "앞, 앞서, 먼저" },
  { kanji: "泥を塗る", hiragana: "どろをぬる", meaning: "먹칠을 하다, 욕을 보이다" },
  { kanji: "拾う", hiragana: "ひろう", meaning: "줍다, 골라내다" },
  { kanji: "原稿", hiragana: "げんこう", meaning: "원고" },
  { kanji: "対象", hiragana: "たいしょう", meaning: "대상, 상대" },
  { kanji: "実施", hiragana: "じっし", meaning: "실시" },
  { kanji: "手直し", hiragana: "てなおし", meaning: "고치다" },
  { kanji: "安い", hiragana: "やすい", meaning: "싸다, 편하다" },
  { kanji: "割", hiragana: "わり", meaning: "나눔, 몫, 비율" },
  { kanji: "買い切り", hiragana: "かいきり", meaning: "모두 사버림, 모두 사다, 매절" },
  { kanji: "品", hiragana: "しな", meaning: "물건, 상품, 물품" },
  { kanji: "間", hiragana: "あいだ", meaning: "사이, 간격, 틈" },
  { kanji: "暮れる", hiragana: "くれる", meaning: "저물다, 해가 저물다" },
  { kanji: "続ける", hiragana: "つづける", meaning: "계속하다, 연결하다, 연달아 하다" },
  { kanji: "研究", hiragana: "けんきゅう", meaning: "연구" },
  { kanji: "世界", hiragana: "せかい", meaning: "세계" },
  { kanji: "目当て", hiragana: "めあて", meaning: "목표, 목적, 표준" },
  { kanji: "違う", hiragana: "ちがう", meaning: "다르다, 차이가 있다" },
  { kanji: "知る", hiragana: "しる", meaning: "알다" },
  { kanji: "雪", hiragana: "ゆき", meaning: "눈" },
  { kanji: "土地", hiragana: "とち", meaning: "토지, 땅" },
  { kanji: "部屋", hiragana: "へや", meaning: "방" },
  { kanji: "欲しい", hiragana: "ほしい", meaning: "갖고 싶다, 바라다, 요망하다" },
  { kanji: "窓", hiragana: "まど", meaning: "창문" },
  { kanji: "食後", hiragana: "しょくご", meaning: "식후" },
  { kanji: "階段", hiragana: "かいだん", meaning: "계단" },
  { kanji: "一食", hiragana: "いっしょく", meaning: "한 끼" },
  { kanji: "数える", hiragana: "かぞえる", meaning: "세다, 계산하다, 열거하다" },
  { kanji: "最後", hiragana: "さいご", meaning: "최후, 마지막, 끝" },
  { kanji: "開く", hiragana: "あく, ひらく", meaning: "열다, 열리다" },
  { kanji: "駐車場", hiragana: "ちゅうしゃじょう", meaning: "주차장" },
  { kanji: "眠る", hiragana: "ねむる", meaning: "잠자다, 자다, 잠들다" },
  { kanji: "後ろ", hiragana: "うしろ", meaning: "뒤, 나중" },
  { kanji: "向け", hiragana: "むけ", meaning: "대상, 용, ~용" },
  { kanji: "旅先", hiragana: "たびさき", meaning: "여행지, 여행 중 머무는 장소" },
  { kanji: "登る", hiragana: "のぼる", meaning: "올라가다, 오르다" },
  { kanji: "放送", hiragana: "ほうそう", meaning: "방송" },
  { kanji: "電話", hiragana: "でんわ", meaning: "전화" },
  { kanji: "生食", hiragana: "せいしょく", meaning: "생식" },
  { kanji: "肩", hiragana: "かた", meaning: "어깨" },
  { kanji: "初夢", hiragana: "はつゆめ", meaning: "첫꿈, 새해 첫꿈" },
  { kanji: "当てる", hiragana: "あてる", meaning: "맞히다, 맞추다, 대다" },
  { kanji: "直ぐ", hiragana: "すぐ", meaning: "곧, 즉시, 바로" },
  { kanji: "左", hiragana: "ひだり", meaning: "왼쪽" },
  { kanji: "耳", hiragana: "みみ", meaning: "귀" },
  { kanji: "触る", hiragana: "さわる", meaning: "접촉하다, 손으로 만지다, 관여하다, 거슬리다" },
  { kanji: "僕", hiragana: "ぼく", meaning: "나" },
  { kanji: "英語", hiragana: "えいご", meaning: "영어" },
  { kanji: "散歩", hiragana: "さんぽ", meaning: "산책" },
  { kanji: "速成", hiragana: "そくせい", meaning: "속성, 빨리 이루어짐" },
  { kanji: "図書館", hiragana: "としょかん", meaning: "도서관" },
  { kanji: "脱退", hiragana: "だったい", meaning: "탈퇴" },
  { kanji: "持ち歩く", hiragana: "もちあるく", meaning: "들고 다니다, 가지고 다니다" },
  { kanji: "氏名", hiragana: "しめい", meaning: "성명" },
  { kanji: "お客さん", hiragana: "おきゃくさん", meaning: "손님" },
  { kanji: "斜線", hiragana: "しゃせん", meaning: "사선" },
  { kanji: "立て込む", hiragana: "たてこむ", meaning: "붐비다, 혼잡하다" },
  { kanji: "引く", hiragana: "ひく", meaning: "끌다, 긋다, 빼다" },
  { kanji: "高い", hiragana: "たかい", meaning: "높다, 비싸다" },
  { kanji: "勉強", hiragana: "べんきょう", meaning: "공부" },
  { kanji: "低い", hiragana: "ひくい", meaning: "낮다, 작다, 짧다" },
  { kanji: "過ぎる", hiragana: "すぎる", meaning: "지나치다, 지나다, 끝나다, 너무 ~ 하다" },
  { kanji: "流れる", hiragana: "ながれる", meaning: "흐르다, 흘러내리다, 흘러가다" },
  { kanji: "講義", hiragana: "こうぎ", meaning: "강의" },
  { kanji: "美しい", hiragana: "うつくしい", meaning: "아름답다, 곱다" },
  { kanji: "過労", hiragana: "かろう", meaning: "과로" },
  { kanji: "園内", hiragana: "えんない", meaning: "원내" },
  { kanji: "火", hiragana: "ひ", meaning: "불" },
  { kanji: "国", hiragana: "くに", meaning: "나라, 국가" },
];
