// lib/words_06_10.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_06_10: Word[] = [
  { kanji: "立つ", hiragana: "たつ", meaning: "서다, 일어서다" },
  { kanji: "先", hiragana: "さき", meaning: "앞, 선두, 전방, 먼저, 끄트머리" },
  { kanji: "スプーン", hiragana: "", meaning: "스푼, 숟가락" },
  { kanji: "毎晩", hiragana: "まいばん", meaning: "매일 밤" },
  { kanji: "沢山", hiragana: "たくさん", meaning: "많음, 충분함" },
  { kanji: "近い", hiragana: "ちかい", meaning: "가깝다" },
  { kanji: "静か", hiragana: "しずか", meaning: "조용함" },
  { kanji: "新聞", hiragana: "しんぶん", meaning: "신문" },
  { kanji: "本", hiragana: "ほん", meaning: "책" },
  { kanji: "いくら", hiragana: "", meaning: "얼마, 어느 정도, 아무리" },
  { kanji: "持つ", hiragana: "もつ", meaning: "지니다, 쥐다, 들다, 가지다" },
  { kanji: "買う", hiragana: "かう", meaning: "사다, 구입하다" },
  { kanji: "秋", hiragana: "あき", meaning: "가을" },
  { kanji: "靴下", hiragana: "くつした", meaning: "양말" },
  { kanji: "お茶", hiragana: "おちゃ", meaning: "차" },
  { kanji: "どんな", hiragana: "", meaning: "어떠한, 어떤" },
  { kanji: "水", hiragana: "みず", meaning: "물" },
  { kanji: "ナイフ", hiragana: "", meaning: "나이프" },
  { kanji: "顔", hiragana: "かお", meaning: "얼굴" },
  { kanji: "昨日", hiragana: "きのう", meaning: "어제" },
  { kanji: "切符", hiragana: "きっぷ", meaning: "티켓, 표" },
  { kanji: "昼ご飯", hiragana: "ひるごはん", meaning: "점심밥, 점심식사" },
  { kanji: "休み", hiragana: "やすみ", meaning: "휴식, 휴일, 휴가, 방학" },
  { kanji: "色々", hiragana: "いろいろ", meaning: "여러 종류, 다양한, 가지각색" },
  { kanji: "銀行", hiragana: "ぎんこう", meaning: "은행" },
  { kanji: "門", hiragana: "もん", meaning: "문, 대문" },
  { kanji: "留学生", hiragana: "りゅうがくせい", meaning: "유학생" },
  { kanji: "丈夫", hiragana: "じょうぶ", meaning: "장부, 건강함, 튼튼함" },
  { kanji: "川", hiragana: "かわ", meaning: "강" },
  { kanji: "年", hiragana: "とし", meaning: "년, 해" },
  { kanji: "住む", hiragana: "すむ", meaning: "살다, 거주하다" },
  { kanji: "狭い", hiragana: "せまい", meaning: "좁다" },
  { kanji: "飲む", hiragana: "のむ", meaning: "마시다, 복용하다" },
  { kanji: "一つ", hiragana: "ひとつ", meaning: "하나, 한 개" },
  { kanji: "上がる", hiragana: "あがる", meaning: "오르다, 올라가다" },
  { kanji: "一日", hiragana: "いちにち", meaning: "일일, 하루" },
  { kanji: "七", hiragana: "しち", meaning: "7" },
  { kanji: "一番", hiragana: "いちばん", meaning: "가장, 제일, 첫째" },
  { kanji: "山", hiragana: "やま", meaning: "산" },
  { kanji: "十", hiragana: "じゅう", meaning: "10" },
  { kanji: "降る", hiragana: "ふる", meaning: "내리다, 오다, (비,눈 등이) 내리다" },
  { kanji: "売る", hiragana: "うる", meaning: "팔다, 판매하다" },
  { kanji: "何", hiragana: "なに", meaning: "무엇, 뭐" },
  { kanji: "果物", hiragana: "くだもの", meaning: "과일" },
  { kanji: "問題", hiragana: "もんだい", meaning: "문제" },
  { kanji: "建物", hiragana: "たてもの", meaning: "건물" },
  { kanji: "手紙", hiragana: "てがみ", meaning: "편지" },
  { kanji: "毎週", hiragana: "まいしゅう", meaning: "매주" },
  { kanji: "ありがとうございます", hiragana: "", meaning: "감사합니다" },
  { kanji: "上着", hiragana: "うわぎ", meaning: "겉옷, 상의" },
  { kanji: "痛い", hiragana: "いたい", meaning: "아프다" },
  { kanji: "弟", hiragana: "おとうと", meaning: "남동생" },
  { kanji: "二日", hiragana: "ふつか", meaning: "이틀, 2일" },
  { kanji: "車", hiragana: "くるま", meaning: "차, 자동차" },
  { kanji: "子供", hiragana: "こども", meaning: "아이, 어린이, 자식" },
  { kanji: "野菜", hiragana: "やさい", meaning: "야채" },
  { kanji: "上", hiragana: "うえ", meaning: "위, 위쪽" },
  { kanji: "良い", hiragana: "よい, いい", meaning: "좋다, ~하기 좋다" },
  { kanji: "分かる", hiragana: "わかる", meaning: "알다, 이해하다" },
  { kanji: "汚い", hiragana: "きたない", meaning: "더럽다, 불결하다" },
  { kanji: "習う", hiragana: "ならう", meaning: "배우다, 익히다" },
  { kanji: "終わる", hiragana: "おわる", meaning: "끝나다, 마치다" },
  { kanji: "重い", hiragana: "おもい", meaning: "무겁다" },
  { kanji: "夕方", hiragana: "ゆうがた", meaning: "저녁때, 해질녁" },
  { kanji: "所", hiragana: "ところ", meaning: "곳, 장소" },
  { kanji: "緑", hiragana: "みどり", meaning: "녹색, 초록" },
  { kanji: "宿題", hiragana: "しゅくだい", meaning: "숙제" },
  { kanji: "借りる", hiragana: "かりる", meaning: "빌리다" },
  { kanji: "広い", hiragana: "ひろい", meaning: "넓다" },
  { kanji: "消す", hiragana: "けす", meaning: "끄다, 지우다, 없애다" },
  { kanji: "余り", hiragana: "あまり", meaning: "여분, 나머지, 별로, 그다지, 너무, 지나치게" },
  { kanji: "時間", hiragana: "じかん", meaning: "시간" },
  { kanji: "病気", hiragana: "びょうき", meaning: "병, 질병" },
  { kanji: "消える", hiragana: "きえる", meaning: "꺼지다, 사라지다, 없어지다" },
  { kanji: "死ぬ", hiragana: "しぬ", meaning: "죽다" },
