// lib/words_31_34.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_31_34: Word[] = [
  { kanji: "来年", hiragana: "らいねん", meaning: "내년" },
  { kanji: "返す", hiragana: "かえす", meaning: "되돌리다, 돌려주다, 갚다" },
  { kanji: "辞書", hiragana: "じしょ", meaning: "사전" },
  { kanji: "掛かる", hiragana: "かかる", meaning: "걸리다, 들다, 매달리다" },
  { kanji: "方", hiragana: "ほう", meaning: "방면, 방향, 편, 쪽" },
  { kanji: "グラス", hiragana: "", meaning: "글라스, 유리컵" },
  { kanji: "二十日", hiragana: "はつか", meaning: "20일" },
  { kanji: "食べる", hiragana: "たべる", meaning: "먹다" },
  { kanji: "書く", hiragana: "かく", meaning: "쓰다" },
  { kanji: "隣", hiragana: "となり", meaning: "이웃, 옆" },
  { kanji: "音楽", hiragana: "おんがく", meaning: "음악" },
  { kanji: "元気", hiragana: "げんき", meaning: "원기, 기력, 건강함" },
  { kanji: "今", hiragana: "いま", meaning: "지금, 이제, 현재" },
  { kanji: "明後日", hiragana: "あさって", meaning: "모레" },
  { kanji: "部屋", hiragana: "へや", meaning: "방" },
  { kanji: "大好き", hiragana: "だいすき", meaning: "매우 좋아하다, 사랑하다" },
  { kanji: "どうして", hiragana: "", meaning: "어째서, 왜" },
  { kanji: "洗う", hiragana: "あらう", meaning: "씻다" },
  { kanji: "一日", hiragana: "ついたち", meaning: "1일, 초하루" },
  { kanji: "呼ぶ", hiragana: "よぶ", meaning: "부르다" },
  { kanji: "こんな", hiragana: "", meaning: "이러한, 이와 같은, 이런" },
  { kanji: "皆さん", hiragana: "みなさん", meaning: "여러분" },
  { kanji: "覚える", hiragana: "おぼえる", meaning: "기억하다, 외우다, 배우다, 느끼다" },
  { kanji: "三", hiragana: "さん", meaning: "3" },
  { kanji: "綺麗", hiragana: "きれい", meaning: "고움, 예쁨, 깨끗함" },
  { kanji: "五つ", hiragana: "いつつ", meaning: "5개, 다섯" },
  { kanji: "それ", hiragana: "", meaning: "그것" },
  { kanji: "空", hiragana: "そら", meaning: "하늘" },
  { kanji: "暇", hiragana: "ひま", meaning: "한가한, 여유로운, 틈, 짬" },
  { kanji: "医者", hiragana: "いしゃ", meaning: "의사" },
  { kanji: "なぜ", hiragana: "", meaning: "왜, 어째서" },
  { kanji: "赤い", hiragana: "あかい", meaning: "붉다, 빨강, 빨갛다" },
  { kanji: "速い", hiragana: "はやい", meaning: "빠르다" },
  { kanji: "良い", hiragana: "よい", meaning: "좋다, 뛰어나다" },
  { kanji: "二", hiragana: "に", meaning: "2" },
  { kanji: "貸す", hiragana: "かす", meaning: "빌려주다" },
  { kanji: "九", hiragana: "きゅう", meaning: "9" },
  { kanji: "角", hiragana: "かど", meaning: "귀퉁이, 구석, 모퉁이, 모서리" },
  { kanji: "頭", hiragana: "あたま", meaning: "머리" },
  { kanji: "八百屋", hiragana: "やおや", meaning: "야채 가게" },
  { kanji: "どこ", hiragana: "", meaning: "어디" },
  { kanji: "段々", hiragana: "だんだん", meaning: "차차, 점점" },
  { kanji: "男の子", hiragana: "おとこのこ", meaning: "남자아이" },
  { kanji: "中", hiragana: "なか", meaning: "가운데, 안, 중, 속" },
  { kanji: "難しい", hiragana: "むずかしい", meaning: "어렵다" },
  { kanji: "遠い", hiragana: "とおい", meaning: "멀다, 친하지 않다, 소원하다" },
  { kanji: "スポーツ", hiragana: "", meaning: "스포츠" },
  { kanji: "肉", hiragana: "にく", meaning: "고기" },
  { kanji: "四日", hiragana: "よっか", meaning: "4일, 나흘" },
  { kanji: "忙しい", hiragana: "いそがしい", meaning: "바쁘다" },
  { kanji: "大学", hiragana: "だいがく", meaning: "대학, 대학교" },
  { kanji: "兄", hiragana: "あに", meaning: "형, 오빠" },
  { kanji: "ネクタイ", hiragana: "", meaning: "넥타이" },
  { kanji: "来月", hiragana: "らいげつ", meaning: "다음 달" },
];