// lib/words_21_25.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_21_25: Word[] = [
  { kanji: "百", hiragana: "ひゃく", meaning: "백, 100" },
  { kanji: "真っ直ぐ", hiragana: "まっすぐ", meaning: "곧장, 쭉, 똑바로, 정면" },
  { kanji: "面白い", hiragana: "おもしろい", meaning: "재밌다, 재미있다" },
  { kanji: "洋服", hiragana: "ようふく", meaning: "양복" },
  { kanji: "雑誌", hiragana: "ざっし", meaning: "잡지" },
  { kanji: "お兄さん", hiragana: "おにいさん", meaning: "형, 오빠" },
  { kanji: "学校", hiragana: "がっこう", meaning: "학교" },
  { kanji: "毎日", hiragana: "まいにち", meaning: "매일, 날마다" },
  { kanji: "天気", hiragana: "てんき", meaning: "날씨" },
  { kanji: "男", hiragana: "おとこ", meaning: "남자" },
  { kanji: "おばあさん", hiragana: "", meaning: "할머니" },
  { kanji: "エレベーター", hiragana: "", meaning: "엘리베이터" },
  { kanji: "閉まる", hiragana: "しまる", meaning: "닫히다" },
  { kanji: "まだ", hiragana: "", meaning: "아직, 계속" },
  { kanji: "鉛筆", hiragana: "えんぴつ", meaning: "연필" },
  { kanji: "損する", hiragana: "そんする", meaning: "손해보다, 손해를 보다" },
  { kanji: "治る", hiragana: "なおる", meaning: "낫다, 치료되다" },
  { kanji: "一着", hiragana: "いっちゃく", meaning: "한 벌, 일착, 옷을 입음" },
  { kanji: "文房具", hiragana: "ぶんぼうぐ", meaning: "문방구" },
  { kanji: "似る", hiragana: "にる", meaning: "닮다, 비슷하다" },
  { kanji: "通う", hiragana: "かよう", meaning: "다니다, 통하다, 마음이 상통하다" },
  { kanji: "事", hiragana: "こと", meaning: "일, 사항" },
  { kanji: "当たる", hiragana: "あたる", meaning: "맞다" },
  { kanji: "予報", hiragana: "よほう", meaning: "예보, 미리 알리는 것" },
  { kanji: "見送る", hiragana: "みおくる", meaning: "가는 것을 바라보다, 배웅하다" },
  { kanji: "各階", hiragana: "かくかい", meaning: "각 층" },
  { kanji: "止まる", hiragana: "とまる", meaning: "멈추다, 멎다, 정지하다" },
  { kanji: "傷", hiragana: "きず", meaning: "상처, 다친 데" },
  { kanji: "町", hiragana: "まち", meaning: "마을, 거리" },
  { kanji: "先週", hiragana: "せんしゅう", meaning: "지난 주, 저번 주" },
  { kanji: "学生", hiragana: "がくせい", meaning: "학생" },
  { kanji: "どうも", hiragana: "", meaning: "정말, 참, 아무래도, 어딘가, 어쩐지, 감사합니다" },
  { kanji: "何方", hiragana: "どなた", meaning: "어느 분, 누구" },
  { kanji: "低い", hiragana: "ひくい", meaning: "낮다, 작다, 얕다" },
  { kanji: "教える", hiragana: "おしえる", meaning: "가르치다" },
  { kanji: "美味しい", hiragana: "おいしい", meaning: "맛있다" },
  { kanji: "明日", hiragana: "あした", meaning: "내일" },
  { kanji: "誕生日", hiragana: "たんじょうび", meaning: "생일" },
  { kanji: "警官", hiragana: "けいかん", meaning: "경관, 경찰관" },
  { kanji: "はい", hiragana: "", meaning: "네, 예" },
  { kanji: "一時", hiragana: "いちじ", meaning: "일시, 한때, 한동안" },
  { kanji: "先生", hiragana: "せんせい", meaning: "선생님" },
  { kanji: "漢字", hiragana: "かんじ", meaning: "한자" },
  { kanji: "美術館", hiragana: "びじゅつかん", meaning: "미술관" },
  { kanji: "恋", hiragana: "こい", meaning: "사랑, 연애" },
  { kanji: "時代", hiragana: "じだい", meaning: "시대, 오래되어 낡은 느낌" },
  { kanji: "冷める", hiragana: "さめる", meaning: "식다, 차가워지다" },
  { kanji: "振り返る", hiragana: "ふりかえる", meaning: "뒤돌아보다, 회고하다" },
  { kanji: "教卓", hiragana: "きょうたく", meaning: "교탁" },
  { kanji: "様", hiragana: "さま", meaning: "모양, 상태, 모습" },
  { kanji: "猛勉強", hiragana: "もうべんきょう", meaning: "맹공부, 아주 열심히 공부하는 것" },
  { kanji: "生きる", hiragana: "いきる", meaning: "살다, 생명을 유지하다, 생계를 유지하다" },
  { kanji: "晴れる", hiragana: "はれる", meaning: "개다, 사라지다, 풀리다" },
  { kanji: "呼ぶ", hiragana: "よぶ", meaning: "부르다, 소리내어 부르다" },
  { kanji: "呼び止める", hiragana: "よびとめる", meaning: "불러서 멈춰세우다" },
  { kanji: "早速", hiragana: "さっそく", meaning: "신속한 것, 곧, 즉시" },
  { kanji: "参る", hiragana: "まいる", meaning: "가다, 오다, 行く、来る의 겸양적 표현" },
  { kanji: "鍵", hiragana: "かぎ", meaning: "열쇠" },
  { kanji: "おじさん", hiragana: "", meaning: "아저씨, 백부, 숙부" },
  { kanji: "無い", hiragana: "ない", meaning: "없다" },
  { kanji: "番号", hiragana: "ばんごう", meaning: "번호" },
  { kanji: "八", hiragana: "はち", meaning: "8" },
  { kanji: "トイレ", hiragana: "", meaning: "화장실" },
  { kanji: "風邪", hiragana: "かぜ", meaning: "감기" },
  { kanji: "もしもし", hiragana: "", meaning: "여보세요" },
  { kanji: "今週", hiragana: "こんしゅう", meaning: "금주, 이번 주" },
  { kanji: "体", hiragana: "からだ", meaning: "몸, 육체, 신체" },
  { kanji: "話す", hiragana: "はなす", meaning: "말하다, 이야기하다" },
  { kanji: "いいえ", hiragana: "", meaning: "아니요, 아니" },
  { kanji: "白い", hiragana: "しろい", meaning: "하얗다, 희다" },
  { kanji: "でも", hiragana: "", meaning: "~지라도, 하지만" },
  { kanji: "友達", hiragana: "ともだち", meaning: "친구" },
  { kanji: "解錠", hiragana: "かいじょう", meaning: "자물쇠를 열다, 잠겨있는 자물쇠를 여는 것" },
  { kanji: "十分", hiragana: "じゅっぷん", meaning: "10분" },
  { kanji: "世代", hiragana: "せだい", meaning: "세대, 어떤 연령층" },
  { kanji: "行ける", hiragana: "いける", meaning: "갈 수 있다" },
  { kanji: "授業", hiragana: "じゅぎょう", meaning: "수업" },
  { kanji: "出会う", hiragana: "であう", meaning: "우연히 만나다, 우연히 마주치다" },
  { kanji: "携帯", hiragana: "けいたい", meaning: "휴대, 휴대폰, 휴대전화" },
  { kanji: "偶然", hiragana: "ぐうぜん", meaning: "우연, 우연히" },
  { kanji: "労働", hiragana: "ろうどう", meaning: "노동" },
  { kanji: "土曜日", hiragana: "どようび", meaning: "토요일" },
  { kanji: "夜更かし", hiragana: "よふかし", meaning: "밤늦게까지 안 자는 것, 밤늦도록 깨어 있는 것" },
  { kanji: "毒", hiragana: "どく", meaning: "독" },
  { kanji: "割る", hiragana: "わる", meaning: "나누다" },
  { kanji: "歯", hiragana: "は", meaning: "이, 이빨" },
  { kanji: "笑う", hiragana: "わらう", meaning: "웃다" },
  { kanji: "軽い", hiragana: "かるい", meaning: "가볍다" },
  { kanji: "浴びる", hiragana: "あびる", meaning: "뒤집어쓰다, 샤워하다, 끼얹다" },
  { kanji: "図書館", hiragana: "としょかん", meaning: "도서관" },
  { kanji: "どの", hiragana: "", meaning: "어느, 어떤" },
  { kanji: "暑い", hiragana: "あつい", meaning: "덥다" },
  { kanji: "こんばんは", hiragana: "", meaning: "안녕하세요, 저녁 인사" },
  { kanji: "円", hiragana: "えん", meaning: "엔, 둥근 것, 원" },
  { kanji: "国", hiragana: "くに", meaning: "나라, 국가" },
  { kanji: "ちょっと", hiragana: "", meaning: "잠깐, 조금, 여보세요" },
  { kanji: "机", hiragana: "つくえ", meaning: "책상" },
  { kanji: "ギター", hiragana: "", meaning: "기타" },
  { kanji: "甘い", hiragana: "あまい", meaning: "달다, 달콤하다" },
  { kanji: "開ける", hiragana: "あける", meaning: "열다" },
  { kanji: "耳", hiragana: "みみ", meaning: "귀" },
  { kanji: "安い", hiragana: "やすい", meaning: "싸다, 편하다" },
  { kanji: "足取り", hiragana: "あしどり", meaning: "걸음, 발걸음, 경로" },
  { kanji: "大嫌い", hiragana: "だいきらい", meaning: "몹시 싫음, 질색" },
  { kanji: "借り出す", hiragana: "かりだす", meaning: "빌려내다, 동원하다" },
  { kanji: "給料", hiragana: "きゅうりょう", meaning: "급료, 봉급" },
  { kanji: "もっと", hiragana: "", meaning: "더, 더욱, 좀 더" },
  { kanji: "ぼやく", hiragana: "", meaning: "투덜거리다, 불평하다, 우는 소리를 하다" },
  { kanji: "格別", hiragana: "かくべつ", meaning: "특별히, 각별히, 유난히" },
  { kanji: "お邪魔します", hiragana: "おじゃまします", meaning: "실례합니다, 실례하겠습니다" },
  { kanji: "項目", hiragana: "こうもく", meaning: "항목, 표제어" },
  { kanji: "数値", hiragana: "すうち", meaning: "수치, 값" },
  { kanji: "表示", hiragana: "ひょうじ", meaning: "표시, 겉에 드러내보임" },
  { kanji: "送る", hiragana: "おくる", meaning: "보내다, 부치다, 송금하다" },
  { kanji: "楽器", hiragana: "がっき", meaning: "악기" },
  { kanji: "寄る", hiragana: "よる", meaning: "접근하다, 들르다" },
  { kanji: "古い", hiragana: "ふるい", meaning: "오래되다, 낡다" },
  { kanji: "時計", hiragana: "とけい", meaning: "시계" },
  { kanji: "テスト", hiragana: "", meaning: "테스트" },
  { kanji: "会う", hiragana: "あう", meaning: "만나다, 대면하다" },
  { kanji: "あそこ", hiragana: "", meaning: "저기, 저곳" },
  { kanji: "電車", hiragana: "でんしゃ", meaning: "전차, 전철" },
  { kanji: "雪", hiragana: "ゆき", meaning: "눈" },
  { kanji: "好き", hiragana: "すき", meaning: "좋아함, 좋아하다" },
  { kanji: "歩く", hiragana: "あるく", meaning: "걷다" },
  { kanji: "来週", hiragana: "らいしゅう", meaning: "다음 주" },
  { kanji: "辛い", hiragana: "からい", meaning: "맵다" },
  { kanji: "少し", hiragana: "すこし", meaning: "조금, 약간, 좀" },
  { kanji: "デパート", hiragana: "", meaning: "백화점" },
  { kanji: "鞄", hiragana: "かばん", meaning: "가방" },
  { kanji: "今時", hiragana: "いまどき", meaning: "요즘, 이맘때" },
  { kanji: "行われる", hiragana: "おこなわれる", meaning: "행하여지다, 실시되다" },
  { kanji: "考え", hiragana: "かんがえ", meaning: "생각" },
  { kanji: "続き", hiragana: "つづき", meaning: "계속, 이음, 잇따름" },
  { kanji: "狂う", hiragana: "くるう", meaning: "미치다, 이상해지다, 고장나다" },
  { kanji: "苦手", hiragana: "にがて", meaning: "잘하지 못함, 다루기 어렵고 싫은 상대" },
  { kanji: "成績", hiragana: "せいせき", meaning: "성적" },
  { kanji: "偏重", hiragana: "へんちょう", meaning: "편중, 지나치게 중시함" },
  { kanji: "驚く", hiragana: "おどろく", meaning: "놀라다" },
  { kanji: "場所", hiragana: "ばしょ", meaning: "장소, 자리" },
  { kanji: "週末", hiragana: "しゅうまつ", meaning: "주말" },
  { kanji: "遅れる", hiragana: "おくれる", meaning: "늦다, 시각을 지나다" },
  { kanji: "込み合う", hiragana: "こみあう", meaning: "붐비다, 혼잡하다, 북적이다" },
  { kanji: "遅刻", hiragana: "ちこく", meaning: "지각, 정해진 시각보다 늦게 도착하는 것" },
  { kanji: "積もる", hiragana: "つもる", meaning: "쌓이다, 어림하다" },
  { kanji: "中身", hiragana: "なかみ", meaning: "속, 속에 든 것, 내용물" },
  { kanji: "寿司", hiragana: "すし", meaning: "스시, 초밥" },
  { kanji: "引っ張り出す", hiragana: "ひっぱりだす", meaning: "끄집어내다, 억지로 나오게 하다" },
  { kanji: "急ぐ", hiragana: "いそぐ", meaning: "서두르다, 빨리 도착하려고 하다" },
];
