// lib/words_26_30.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_26_30: Word[] = [
  { kanji: "外国人", hiragana: "がいこくじん", meaning: "외국인" },
  { kanji: "地下鉄", hiragana: "ちかてつ", meaning: "지하철" },
  { kanji: "先月", hiragana: "せんげつ", meaning: "저번 달, 지난 달" },
  { kanji: "見せる", hiragana: "みせる", meaning: "보여주다" },
  { kanji: "財布", hiragana: "さいふ", meaning: "지갑" },
  { kanji: "其方", hiragana: "そちら", meaning: "그쪽" },
  { kanji: "お金", hiragana: "おかね", meaning: "돈, 금전" },
  { kanji: "使う", hiragana: "つかう", meaning: "쓰다, 사용하다, 소비하다" },
  { kanji: "黄色い", hiragana: "きいろい", meaning: "노랗다" },
  { kanji: "午前", hiragana: "ごぜん", meaning: "오전" },
  { kanji: "後", hiragana: "あと", meaning: "뒤, 다음, 후, 나중에" },
  { kanji: "乗る", hiragana: "のる", meaning: "타다, 오르다" },
  { kanji: "台所", hiragana: "だいどころ", meaning: "부엌" },
  { kanji: "大丈夫", hiragana: "だいじょうぶ", meaning: "괜찮음, 걱정없음" },
  { kanji: "東", hiragana: "ひがし", meaning: "동쪽, 동" },
  { kanji: "今晩", hiragana: "こんばん", meaning: "오늘 밤" },
  { kanji: "猫", hiragana: "ねこ", meaning: "고양이" },
  { kanji: "生まれる", hiragana: "うまれる", meaning: "태어나다, 생기다, 발생하다" },
  { kanji: "入口", hiragana: "いりぐち", meaning: "입구" },
  { kanji: "後ろ", hiragana: "うしろ", meaning: "뒤, 뒤쪽" },
  { kanji: "火曜日", hiragana: "かようび", meaning: "화요일" },
  { kanji: "今年", hiragana: "ことし", meaning: "올해, 금년" },
  { kanji: "吸う", hiragana: "すう", meaning: "들이마시다, 빨아들이다, 담배를 피다" },
  { kanji: "父", hiragana: "ちち", meaning: "아버지" },
  { kanji: "公園", hiragana: "こうえん", meaning: "공원" },
  { kanji: "動物", hiragana: "どうぶつ", meaning: "동물" },
  { kanji: "ラジオ", hiragana: "", meaning: "라디오" },
  { kanji: "あんな", hiragana: "", meaning: "저런, 저러한" },
  { kanji: "さようなら", hiragana: "", meaning: "안녕, 안녕히 가세요" },
  { kanji: "コート", hiragana: "", meaning: "코트" },
  { kanji: "写真", hiragana: "しゃしん", meaning: "사진" },
  { kanji: "どうぞ", hiragana: "", meaning: "아무쪼록, 부디, 그럼" },
  { kanji: "閉める", hiragana: "しめる", meaning: "닫다" },
  { kanji: "飛行機", hiragana: "ひこうき", meaning: "비행기" },
  { kanji: "押す", hiragana: "おす", meaning: "밀다, 누르다" },
  { kanji: "シャワー", hiragana: "", meaning: "샤워, 목욕" },
  { kanji: "すみません", hiragana: "", meaning: "실례합니다, 죄송합니다" },
  { kanji: "ペン", hiragana: "", meaning: "펜" },
  { kanji: "駅", hiragana: "えき", meaning: "역, 정거장" },
  { kanji: "読む", hiragana: "よむ", meaning: "읽다" },
  { kanji: "午後", hiragana: "ごご", meaning: "오후" },
  { kanji: "三日", hiragana: "みっか", meaning: "사흘, 3일" },
  { kanji: "位", hiragana: "くらい", meaning: "정도, 만큼, 따위, 지위" },
  { kanji: "姉", hiragana: "あね", meaning: "누나, 언니" },
  { kanji: "色", hiragana: "いろ", meaning: "색, 색채" },
  { kanji: "電話", hiragana: "でんわ", meaning: "전화" },
  { kanji: "石鹸", hiragana: "せっけん", meaning: "비누" },
  { kanji: "磨く", hiragana: "みがく", meaning: "닦다, 윤내다, 연마하다" },
  { kanji: "交番", hiragana: "こうばん", meaning: "파출소" },
  { kanji: "これ", hiragana: "", meaning: "이것, 이" },
  { kanji: "上手", hiragana: "じょうず", meaning: "능숙, 잘함" },
  { kanji: "会社", hiragana: "かいしゃ", meaning: "회사" },
  { kanji: "窓", hiragana: "まど", meaning: "창, 창문" },
  { kanji: "その", hiragana: "", meaning: "그, 저" },
  { kanji: "可愛い", hiragana: "かわいい", meaning: "귀엽다, 사랑스럽다" },
  { kanji: "五日", hiragana: "いつか", meaning: "닷새, 5일" },
  { kanji: "八日", hiragana: "ようか", meaning: "여드레, 8일" },
  { kanji: "入れる", hiragana: "いれる", meaning: "넣다" },
  { kanji: "木", hiragana: "き", meaning: "나무" },
  { kanji: "北", hiragana: "きた", meaning: "북쪽, 북" },
  { kanji: "どれ", hiragana: "", meaning: "어느 것, 어떤 것" },
  { kanji: "また", hiragana: "", meaning: "또, 다시, 그리고" },
  { kanji: "咲く", hiragana: "さく", meaning: "피다, 꽃이 피다" },
  { kanji: "もっと", hiragana: "", meaning: "좀 더, 더, 더욱" },
  { kanji: "前", hiragana: "まえ", meaning: "앞, 이전, 먼저" },
  { kanji: "人", hiragana: "ひと", meaning: "사람" },
  { kanji: "歌う", hiragana: "うたう", meaning: "노래를 부르다, 노래하다" },
  { kanji: "鳥肉", hiragana: "とりにく", meaning: "닭고기" },
  { kanji: "朝", hiragana: "あさ", meaning: "아침" },
  { kanji: "登る", hiragana: "のぼる", meaning: "오르다, 올라가다" },
  { kanji: "見る", hiragana: "みる", meaning: "보다" },
  { kanji: "暗い", hiragana: "くらい", meaning: "어둡다" },
  { kanji: "短い", hiragana: "みじかい", meaning: "짧다" },
  { kanji: "いる", hiragana: "", meaning: "있다, (생물) 있다" },
  { kanji: "とても", hiragana: "", meaning: "매우, 대단히" },
];
