// lib/words_01_05.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_01_05: Word[] = [
  { kanji: "うるさい", hiragana: "うるさい", meaning: "시끄럽다, 귀찮다" },
  { kanji: "手", hiragana: "て", meaning: "손" },
  { kanji: "座る", hiragana: "すわる", meaning: "앉다" },
  { kanji: "悪い", hiragana: "わるい", meaning: "나쁘다, 좋지 않다" },
  { kanji: "紅茶", hiragana: "こうちゃ", meaning: "홍차" },
  { kanji: "上げる", hiragana: "あげる", meaning: "올리다, 얹다" },
  { kanji: "切手", hiragana: "きって", meaning: "우표" },
  { kanji: "買い物", hiragana: "かいもの", meaning: "물건을 삼, 쇼핑" },
  { kanji: "晩ご飯", hiragana: "ばんごはん", meaning: "저녁밥, 저녁 식사" },
  { kanji: "飛ぶ", hiragana: "とぶ", meaning: "날다" },
  { kanji: "起きる", hiragana: "おきる", meaning: "일어나다, 기상하다" },
  { kanji: "ある", hiragana: "ある", meaning: "있다" },
  { kanji: "灰皿", hiragana: "はいざら", meaning: "재떨이" },
  { kanji: "家族", hiragana: "かぞく", meaning: "가족" },
  { kanji: "お姉さん", hiragana: "おねえさん", meaning: "언니, 누나" },
  { kanji: "九日", hiragana: "ここのか", meaning: "9일, 아흐레" },
  { kanji: "言う", hiragana: "いう", meaning: "말하다" },
  { kanji: "セーター", hiragana: "", meaning: "스웨터" },
  { kanji: "聞く", hiragana: "きく", meaning: "듣다, 묻다" },
  { kanji: "お父さん", hiragana: "おとうさん", meaning: "아빠, 아버지" },
  { kanji: "コピー", hiragana: "", meaning: "카피, 복사" },
  { kanji: "風", hiragana: "かぜ", meaning: "바람" },
  { kanji: "庭", hiragana: "にわ", meaning: "정원, 뜰, 마당" },
  { kanji: "二つ", hiragana: "ふたつ", meaning: "두 개, 둘" },
  { kanji: "母", hiragana: "はは", meaning: "엄마, 어머니" },
  { kanji: "入る", hiragana: "はいる", meaning: "들어오다, 들어가다" },
  { kanji: "泳ぐ", hiragana: "およぐ", meaning: "헤엄치다, 수영을 하다" },
  { kanji: "始まる", hiragana: "はじまる", meaning: "시작하다, 개시되다" },
  { kanji: "花", hiragana: "はな", meaning: "꽃" },
  { kanji: "鳥", hiragana: "とり", meaning: "새" },
  { kanji: "池", hiragana: "いけ", meaning: "연못" },
  { kanji: "ポケット", hiragana: "", meaning: "주머니" },
  { kanji: "アパート", hiragana: "", meaning: "아파트" },
  { kanji: "病院", hiragana: "びょういん", meaning: "병원" },
  { kanji: "バス", hiragana: "", meaning: "버스" },
  { kanji: "店", hiragana: "みせ", meaning: "가게, 점포" },
  { kanji: "牛肉", hiragana: "ぎゅうにく", meaning: "소고기" },
  { kanji: "危ない", hiragana: "あぶない", meaning: "위험하다" },
  { kanji: "待つ", hiragana: "まつ", meaning: "기다리다" },
  { kanji: "楽しい", hiragana: "たのしい", meaning: "즐겁다" },
  { kanji: "意味", hiragana: "いみ", meaning: "의미" },
  { kanji: "大変", hiragana: "たいへん", meaning: "몹시, 매우, 큰일, 대사건, 힘듦" },
  { kanji: "置く", hiragana: "おく", meaning: "두다, 놓다" },
  { kanji: "妹", hiragana: "いもうと", meaning: "여동생" },
  { kanji: "明るい", hiragana: "あかるい", meaning: "밝다, 환하다, 명랑하다" },
  { kanji: "大きい", hiragana: "おおきい", meaning: "크다, 많다" },
  { kanji: "二十歳", hiragana: "はたち", meaning: "스무 살" },
  { kanji: "いくつ", hiragana: "いくつ", meaning: "몇 살, 몇 개" },
  { kanji: "小さい", hiragana: "ちいさい", meaning: "작다" },
  { kanji: "嫌い", hiragana: "きらい", meaning: "싫어함, 싫다" },
  { kanji: "背", hiragana: "せ", meaning: "등, 키" },
  { kanji: "寒い", hiragana: "さむい", meaning: "춥다" },
  { kanji: "一昨日", hiragana: "おととい", meaning: "그저께" },
  { kanji: "レストラン", hiragana: "", meaning: "레스토랑" },
  { kanji: "二人", hiragana: "ふたり", meaning: "두 사람, 두 명" },
  { kanji: "薄い", hiragana: "うすい", meaning: "얇다, 싱겁다, 적다" },
  { kanji: "歌", hiragana: "うた", meaning: "노래" },
  { kanji: "椅子", hiragana: "いす", meaning: "의자" },
  { kanji: "大勢", hiragana: "おおぜい", meaning: "많은 사람, 여럿" },
  { kanji: "締める", hiragana: "しめる", meaning: "죄다, 묶다, 매다" },
  { kanji: "今日", hiragana: "きょう", meaning: "오늘" },
  { kanji: "薬", hiragana: "くすり", meaning: "약" },
  { kanji: "次", hiragana: "つぎ", meaning: "다음" },
  { kanji: "牛乳", hiragana: "ぎゅうにゅう", meaning: "우유" },
  { kanji: "パン", hiragana: "", meaning: "빵" },
  { kanji: "西", hiragana: "にし", meaning: "서쪽" },
  { kanji: "魚", hiragana: "さかな", meaning: "생선, 물고기" },
  { kanji: "来る", hiragana: "くる", meaning: "오다" },
  { kanji: "開く", hiragana: "あく, ひらく", meaning: "열리다, 열다" },
  { kanji: "そこ", hiragana: "そこ", meaning: "거기, 그 곳" },
  { kanji: "おばさん", hiragana: "おばさん", meaning: "아주머니, 이모, 숙모, 고모" },
  { kanji: "六日", hiragana: "むいか", meaning: "6일, 엿새" },
  { kanji: "足", hiragana: "あし", meaning: "다리, 발" },
  { kanji: "絵", hiragana: "え", meaning: "그림" },
  { kanji: "車", hiragana: "くるま", meaning: "자동차, 차" },
  { kanji: "走る", hiragana: "はしる", meaning: "달리다" },
  { kanji: "音", hiragana: "おと", meaning: "소리" },
  { kanji: "取り合う", hiragana: "とりあう", meaning: "마주 잡다" },
  { kanji: "喜ぶ", hiragana: "よろこぶ", meaning: "기뻐하다" },
  { kanji: "目", hiragana: "め", meaning: "눈" },
  { kanji: "分業", hiragana: "ぶんぎょう", meaning: "분업" },
  { kanji: "能率", hiragana: "のうりつ", meaning: "능률" },
  { kanji: "特別", hiragana: "とくべつ", meaning: "특별" },
  { kanji: "記念", hiragana: "きねん", meaning: "기념" },
  { kanji: "発行", hiragana: "はっこう", meaning: "발행" },
  { kanji: "行く", hiragana: "いく", meaning: "가다" },
  { kanji: "食べる", hiragana: "たべる", meaning: "먹다" },
  { kanji: "空", hiragana: "そら", meaning: "하늘" },
  { kanji: "時間", hiragana: "じかん", meaning: "시간" },
  { kanji: "早い", hiragana: "はやい", meaning: "빠르다" },
  { kanji: "話", hiragana: "はなし", meaning: "이야기, 말, 대화" },
  { kanji: "上", hiragana: "うえ", meaning: "위" },
  { kanji: "全員", hiragana: "ぜんいん", meaning: "전원" },
  { kanji: "出掛ける", hiragana: "でかける", meaning: "외출하다" },
  { kanji: "友人", hiragana: "ゆうじん", meaning: "친구" },
  { kanji: "船", hiragana: "ふね", meaning: "배" },
  { kanji: "掛かる", hiragana: "かかる", meaning: "걸리다" },
  { kanji: "意見", hiragana: "いけん", meaning: "의견" },
  { kanji: "出す", hiragana: "だす", meaning: "꺼내다" },
  { kanji: "着る", hiragana: "きる", meaning: "입다" },
  { kanji: "校長", hiragana: "こうちょう", meaning: "교장" },
  { kanji: "先生", hiragana: "せんせい", meaning: "선생님" },
  { kanji: "訓話", hiragana: "くんわ", meaning: "훈화" },
  { kanji: "一週間", hiragana: "いっしゅうかん", meaning: "일주일, 일주일 간" },
  { kanji: "帰る", hiragana: "かえる", meaning: "돌아오다, 돌아가다" },
  { kanji: "取る", hiragana: "とる", meaning: "잡다" },
  { kanji: "通り", hiragana: "とおり", meaning: "통함, 길" },
  { kanji: "雨", hiragana: "あめ", meaning: "비" },
  { kanji: "木", hiragana: "き", meaning: "나무" },
  { kanji: "潤う", hiragana: "うるおう", meaning: "촉촉해지다, 윤택해지다" },
  { kanji: "仕事", hiragana: "しごと", meaning: "일" },
  { kanji: "手を付ける", hiragana: "てをつける", meaning: "손을 대다, 손대다" },
  { kanji: "汽車", hiragana: "きしゃ", meaning: "기차" },
  { kanji: "駅", hiragana: "えき", meaning: "역" },
  { kanji: "水", hiragana: "みず", meaning: "물" },
  { kanji: "切る", hiragana: "きる", meaning: "자르다, 끊다" },
  { kanji: "会議", hiragana: "かいぎ", meaning: "회의" },
  { kanji: "散る", hiragana: "ちる", meaning: "꽃잎이 지다, 떨어지다" },
  { kanji: "銃", hiragana: "じゅう", meaning: "총, 총기, 화기" },
  { kanji: "矯める", hiragana: "ためる", meaning: "바르게 고치다, 교정하다" },
  { kanji: "撃つ", hiragana: "うつ", meaning: "쏘다" },
  { kanji: "家", hiragana: "いえ", meaning: "집" },
  { kanji: "向こう", hiragana: "むこう", meaning: "건너편" },
  { kanji: "側", hiragana: "がわ", meaning: "쪽, 측" },
  { kanji: "お金", hiragana: "おかね", meaning: "돈" },
  { kanji: "押し込める", hiragana: "おしこめる", meaning: "억지로 집어넣다, 밀어넣다" },
  { kanji: "私", hiragana: "わたし", meaning: "나, 자신" },
  { kanji: "賃貸", hiragana: "ちんたい", meaning: "임대" },
  { kanji: "住む", hiragana: "すむ", meaning: "살다" },
  { kanji: "通学", hiragana: "つうがく", meaning: "통학" },
  { kanji: "知り合う", hiragana: "しりあう", meaning: "서로 알다, 아는 사이가 되다" },
  { kanji: "客数", hiragana: "きゃくすう", meaning: "객수, 손님 수" },
  { kanji: "減る", hiragana: "へる", meaning: "줄다, 적어지다" },
  { kanji: "堅い", hiragana: "かたい", meaning: "단단하다, 딱딱하다" },
  { kanji: "辞書", hiragana: "じしょ", meaning: "사전" },
  { kanji: "辞書を引く", hiragana: "じしょをひく", meaning: "검색하다, 사전을 찾다" },
  { kanji: "首", hiragana: "くび", meaning: "목" },
  { kanji: "長い", hiragana: "ながい", meaning: "길다" },
  { kanji: "本", hiragana: "ほん", meaning: "책" },
  { kanji: "読む", hiragana: "よむ", meaning: "읽다" },
  { kanji: "一番", hiragana: "いちばん", meaning: "가장, 제일, 첫 번" },
  { kanji: "分かる", hiragana: "わかる", meaning: "알다" },
  { kanji: "机", hiragana: "つくえ", meaning: "책상" },
  { kanji: "子", hiragana: "こ", meaning: "자식, 아이" },
  { kanji: "辺", hiragana: "へん", meaning: "근처, 부근" },
  { kanji: "地理", hiragana: "ちり", meaning: "지리" },
  { kanji: "海外", hiragana: "かいがい", meaning: "해외" },
  { kanji: "反響", hiragana: "はんきょう", meaning: "반향" },
  { kanji: "呼び起こす", hiragana: "よびおこす", meaning: "불러 일으키다" },
  { kanji: "彼", hiragana: "かれ", meaning: "그" },
  { kanji: "結婚", hiragana: "けっこん", meaning: "결혼" },
  { kanji: "疑問点", hiragana: "ぎもんてん", meaning: "의문점" },
  { kanji: "残す", hiragana: "のこす", meaning: "남기다" },
  { kanji: "体", hiragana: "からだ", meaning: "몸, 신체" },
  { kanji: "力", hiragana: "ちから", meaning: "힘" },
  { kanji: "強い", hiragana: "つよい", meaning: "강하다" },
  { kanji: "壁", hiragana: "かべ", meaning: "벽" },
  { kanji: "持たせ掛ける", hiragana: "もたせかける", meaning: "기대다" },
  { kanji: "続く", hiragana: "つづく", meaning: "계속되다" },
  { kanji: "会う", hiragana: "あう", meaning: "만나다" },
  { kanji: "韓国人", hiragana: "かんこくじん", meaning: "한국인" },
  { kanji: "実力", hiragana: "じつりょく", meaning: "실력" },
  { kanji: "互角", hiragana: "ごかく", meaning: "호각" },
  { kanji: "氷", hiragana: "こおり", meaning: "얼음" },
  { kanji: "砕ける", hiragana: "くだける", meaning: "부서지다, 깨지다" },
  { kanji: "立ち上がる", hiragana: "たちあがる", meaning: "일어서다, 일어나다" },
  { kanji: "子供", hiragana: "こども", meaning: "아이, 어린아이" },
  { kanji: "集まる", hiragana: "あつまる", meaning: "모이다" },
  { kanji: "少し", hiragana: "すこし", meaning: "조금" },
  { kanji: "風邪", hiragana: "かぜ", meaning: "감기" },
  { kanji: "飲む", hiragana: "のむ", meaning: "마시다" },
  { kanji: "ご飯", hiragana: "ごはん", meaning: "밥" },
  { kanji: "代わり", hiragana: "かわり", meaning: "대신" },
  { kanji: "赤い", hiragana: "あかい", meaning: "빨갛다, 붉다" },
  { kanji: "染まる", hiragana: "そまる", meaning: "물들다" },
  { kanji: "肉", hiragana: "にく", meaning: "고기, 살" },
  { kanji: "毟る", hiragana: "むしる", meaning: "잡아뜯다, 떼어내다" },
  { kanji: "用", hiragana: "よう", meaning: "일, 볼일" },
  { kanji: "済ます", hiragana: "すます", meaning: "마치다, 해결하다, 끝내다" },
  { kanji: "酒", hiragana: "さけ", meaning: "술" },
  { kanji: "完成", hiragana: "かんせい", meaning: "완성" },
  { kanji: "歩く", hiragana: "あるく", meaning: "걷다" },
  { kanji: "生気", hiragana: "せいき", meaning: "생기" },
  { kanji: "無い", hiragana: "ない", meaning: "없다, 존재하지 않다" },
];
