// lib/words_all.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_all: Word[] = [
  { kanji: "うるさい", hiragana: "", meaning: "시끄럽다, 귀찮다" },
  { kanji: "手", hiragana: "て", meaning: "손" },
  { kanji: "座る", hiragana: "すわる", meaning: "앉다" },
  { kanji: "悪い", hiragana: "わるい", meaning: "나쁘다" },
  { kanji: "紅茶", hiragana: "こうちゃ", meaning: "홍차" },
  { kanji: "上げる", hiragana: "あげる", meaning: "올리다, 얹다" },
  { kanji: "切手", hiragana: "きって", meaning: "수표, 어음, 우표" },
  { kanji: "買い物", hiragana: "かいもの", meaning: "물건을 삼, 쇼핑" },
  { kanji: "晩ご飯", hiragana: "ばんごはん", meaning: "저녁밥, 저녁식사" },
  { kanji: "飛ぶ", hiragana: "とぶ", meaning: "날다" },
  { kanji: "起きる", hiragana: "おきる", meaning: "일어나다, 기상하다" },
  { kanji: "ある", hiragana: "", meaning: "있다, (무생물) 있다" },
  { kanji: "灰皿", hiragana: "はいざら", meaning: "재떨이" },
  { kanji: "家族", hiragana: "かぞく", meaning: "가족" },
  { kanji: "お姉さん", hiragana: "おねえさん", meaning: "언니, 누나" },
  { kanji: "九日", hiragana: "ここのか", meaning: "9일, 아흐레" },
  { kanji: "言う", hiragana: "いう", meaning: "말하다" },
  { kanji: "セーター", hiragana: "", meaning: "스웨터" },
  { kanji: "聞く", hiragana: "きく", meaning: "듣다, 묻다" },
  { kanji: "お父さん", hiragana: "おとうさん", meaning: "아버지" },
  { kanji: "コビー", hiragana: "", meaning: "복사" },
  { kanji: "風", hiragana: "かぜ", meaning: "바람" },
  { kanji: "庭", hiragana: "にわ", meaning: "정원, 뜰, 마당" },
  { kanji: "二つ", hiragana: "ふたつ", meaning: "두 개, 둘" },
  { kanji: "母", hiragana: "はは", meaning: "어머니" },
  { kanji: "入る", hiragana: "はいる", meaning: "들어오다, 들어가다" },
  { kanji: "泳ぐ", hiragana: "およぐ", meaning: "헤엄치다, 수영을 하다" },
  { kanji: "始まる", hiragana: "はじまる", meaning: "시작하다, 개시되다" },
  { kanji: "花", hiragana: "はな", meaning: "꽃" },
  { kanji: "鳥", hiragana: "とり", meaning: "새" },
  { kanji: "池", hiragana: "いけ", meaning: "연못" },
  { kanji: "ポケット", hiragana: "", meaning: "포켓, 주머니" },
  { kanji: "アパート", hiragana: "", meaning: "아파트" },
  { kanji: "病院", hiragana: "びょういん", meaning: "병원" },
  { kanji: "バス", hiragana: "", meaning: "버스" },
  { kanji: "店", hiragana: "みせ", meaning: "가게, 상점, 점포" },
  { kanji: "牛肉", hiragana: "ぎゅうにく", meaning: "소고기" },
  { kanji: "危ない", hiragana: "あぶない", meaning: "위험하다" },
  { kanji: "待つ", hiragana: "まつ", meaning: "기다리다" },
  { kanji: "楽しい", hiragana: "たのしい", meaning: "즐겁다" },
  { kanji: "意味", hiragana: "いみ", meaning: "의미" },
  { kanji: "大変", hiragana: "たいへん", meaning: "몹시, 매우, 대사건, 큰일, 힘듦" },
  { kanji: "置く", hiragana: "おく", meaning: "두다, 놓다" },
  { kanji: "妹", hiragana: "いもうと", meaning: "여동생" },
  { kanji: "明るい", hiragana: "あかるい", meaning: "밝다, 환하다, 명랑하다" },
  { kanji: "大きな", hiragana: "おおきな", meaning: "큰" },
  { kanji: "二十歳", hiragana: "はたち", meaning: "스무 살" },
  { kanji: "いくつ", hiragana: "", meaning: "몇 살, 몇 개" },
  { kanji: "小さい", hiragana: "ちいさい", meaning: "작다" },
  { kanji: "嫌い", hiragana: "きらい", meaning: "싫음, 마음에 들지 않음" },
  { kanji: "背", hiragana: "せ", meaning: "등, 키" },
  { kanji: "寒い", hiragana: "さむい", meaning: "춥다" },
  { kanji: "一昨日", hiragana: "おととい", meaning: "그저께" },
  { kanji: "レストラン", hiragana: "", meaning: "레스토랑" },
  { kanji: "二人", hiragana: "ふたり", meaning: "두 사람, 두 명" },
  { kanji: "薄い", hiragana: "うすい", meaning: "얇다, 싱겁다, 적다" },
  { kanji: "歌", hiragana: "うた", meaning: "노래" },
  { kanji: "椅子", hiragana: "いす", meaning: "의자" },
  { kanji: "大勢", hiragana: "おおぜい", meaning: "많은 사람, 여럿" },
  { kanji: "締める", hiragana: "しめる", meaning: "죄다, 조르다, 매다" },
  { kanji: "今日", hiragana: "きょう", meaning: "오늘" },
  { kanji: "薬", hiragana: "くすり", meaning: "약" },
  { kanji: "次", hiragana: "つぎ", meaning: "다음" },
  { kanji: "牛乳", hiragana: "ぎゅうにゅう", meaning: "우유" },
  { kanji: "パン", hiragana: "", meaning: "빵" },
  { kanji: "西", hiragana: "にし", meaning: "서쪽, 서" },
  { kanji: "魚", hiragana: "さかな", meaning: "물고기, 생선" },
  { kanji: "来る", hiragana: "くる", meaning: "오다" },
  { kanji: "開く", hiragana: "あく", meaning: "열리다, 시작하다, 영업하다" },
  { kanji: "そこ", hiragana: "", meaning: "거기, 그곳" },
  { kanji: "おばさん", hiragana: "", meaning: "아주머니, 숙모, 고모, 이모" },
  { kanji: "六日", hiragana: "むいか", meaning: "6일, 엿새" },
  { kanji: "足", hiragana: "あし", meaning: "발, 다리" },
  { kanji: "絵", hiragana: "え", meaning: "그림" },
  { kanji: "立つ", hiragana: "たつ", meaning: "서다, 일어서다" },
  { kanji: "先", hiragana: "さき", meaning: "앞, 선두, 전방, 먼저, 끄트머리" },
  { kanji: "スプーン", hiragana: "", meaning: "스푼, 숟가락" },
  { kanji: "毎晩", hiragana: "まいばん", meaning: "매일 밤" },
  { kanji: "沢山", hiragana: "たくさん", meaning: "많음, 충분함" },
  { kanji: "近い", hiragana: "ちかい", meaning: "가깝다" },
  { kanji: "静か", hiragana: "しずか", meaning: "조용함" },
  { kanji: "新聞", hiragana: "しんぶん", meaning: "신문" },
  { kanji: "本", hiragana: "ほん", meaning: "책" },
  { kanji: "いくら", hiragana: "", meaning: "얼마, 어느 정도, 아무리" },
  { kanji: "持つ", hiragana: "もつ", meaning: "지니다, 쥐다, 들다, 가지다" },
  { kanji: "買う", hiragana: "かう", meaning: "사다, 구입하다" },
  { kanji: "秋", hiragana: "あき", meaning: "가을" },
  { kanji: "靴下", hiragana: "くつした", meaning: "양말" },
  { kanji: "お茶", hiragana: "おちゃ", meaning: "차" },
  { kanji: "どんな", hiragana: "", meaning: "어떠한, 어떤" },
  { kanji: "水", hiragana: "みず", meaning: "물" },
  { kanji: "ナイフ", hiragana: "", meaning: "나이프" },
  { kanji: "顔", hiragana: "かお", meaning: "얼굴" },
  { kanji: "昨日", hiragana: "きのう", meaning: "어제" },
  { kanji: "切符", hiragana: "きっぷ", meaning: "티켓, 표" },
  { kanji: "昼ご飯", hiragana: "ひるごはん", meaning: "점심밥, 점심식사" },
  { kanji: "休み", hiragana: "やすみ", meaning: "휴식, 휴일, 휴가, 방학" },
  { kanji: "色々", hiragana: "いろいろ", meaning: "여러 종류, 다양한, 가지각색" },
  { kanji: "銀行", hiragana: "ぎんこう", meaning: "은행" },
  { kanji: "門", hiragana: "もん", meaning: "문, 대문" },
  { kanji: "留学生", hiragana: "りゅうがくせい", meaning: "유학생" },
  { kanji: "丈夫", hiragana: "じょうぶ", meaning: "장부, 건강함, 튼튼함" },
  { kanji: "川", hiragana: "かわ", meaning: "강" },
  { kanji: "年", hiragana: "とし", meaning: "년, 해" },
  { kanji: "住む", hiragana: "すむ", meaning: "살다, 거주하다" },
  { kanji: "狭い", hiragana: "せまい", meaning: "좁다" },
  { kanji: "飲む", hiragana: "のむ", meaning: "마시다, 복용하다" },
  { kanji: "一つ", hiragana: "ひとつ", meaning: "하나, 한 개" },
  { kanji: "上がる", hiragana: "あがる", meaning: "오르다, 올라가다" },
  { kanji: "一日", hiragana: "いちにち", meaning: "일일, 하루" },
  { kanji: "七", hiragana: "しち", meaning: "7" },
  { kanji: "一番", hiragana: "いちばん", meaning: "가장, 제일, 첫째" },
  { kanji: "山", hiragana: "やま", meaning: "산" },
  { kanji: "十", hiragana: "じゅう", meaning: "10" },
  { kanji: "降る", hiragana: "ふる", meaning: "내리다, 오다, (비,눈 등이) 내리다" },
  { kanji: "売る", hiragana: "うる", meaning: "팔다, 판매하다" },
  { kanji: "何", hiragana: "なに", meaning: "무엇, 뭐" },
  { kanji: "果物", hiragana: "くだもの", meaning: "과일" },
  { kanji: "問題", hiragana: "もんだい", meaning: "문제" },
  { kanji: "建物", hiragana: "たてもの", meaning: "건물" },
  { kanji: "手紙", hiragana: "てがみ", meaning: "편지" },
  { kanji: "毎週", hiragana: "まいしゅう", meaning: "매주" },
  { kanji: "ありがとうございます", hiragana: "", meaning: "감사합니다" },
  { kanji: "上着", hiragana: "うわぎ", meaning: "겉옷, 상의" },
  { kanji: "痛い", hiragana: "いたい", meaning: "아프다" },
  { kanji: "弟", hiragana: "おとうと", meaning: "남동생" },
  { kanji: "二日", hiragana: "ふつか", meaning: "이틀, 2일" },
  { kanji: "車", hiragana: "くるま", meaning: "차, 자동차" },
  { kanji: "子供", hiragana: "こども", meaning: "아이, 어린이, 자식" },
  { kanji: "野菜", hiragana: "やさい", meaning: "야채" },
  { kanji: "上", hiragana: "うえ", meaning: "위, 위쪽" },
  { kanji: "良い", hiragana: "よい, いい", meaning: "좋다, ~하기 좋다" },
  { kanji: "分かる", hiragana: "わかる", meaning: "알다, 이해하다" },
  { kanji: "汚い", hiragana: "きたない", meaning: "더럽다, 불결하다" },
  { kanji: "習う", hiragana: "ならう", meaning: "배우다, 익히다" },
  { kanji: "終わる", hiragana: "おわる", meaning: "끝나다, 마치다" },
  { kanji: "重い", hiragana: "おもい", meaning: "무겁다" },
  { kanji: "夕方", hiragana: "ゆうがた", meaning: "저녁때, 해질녁" },
  { kanji: "所", hiragana: "ところ", meaning: "곳, 장소" },
  { kanji: "緑", hiragana: "みどり", meaning: "녹색, 초록" },
  { kanji: "宿題", hiragana: "しゅくだい", meaning: "숙제" },
  { kanji: "借りる", hiragana: "かりる", meaning: "빌리다" },
  { kanji: "広い", hiragana: "ひろい", meaning: "넓다" },
  { kanji: "消す", hiragana: "けす", meaning: "끄다, 지우다, 없애다" },
  { kanji: "余り", hiragana: "あまり", meaning: "여분, 나머지, 별로, 그다지, 너무, 지나치게" },
  { kanji: "時間", hiragana: "じかん", meaning: "시간" },
  { kanji: "病気", hiragana: "びょうき", meaning: "병, 질병" },
  { kanji: "消える", hiragana: "きえる", meaning: "꺼지다, 사라지다, 없어지다" },
  { kanji: "死ぬ", hiragana: "しぬ", meaning: "죽다" },
  { kanji: "四", hiragana: "し, よん", meaning: "4" },
  { kanji: "夕飯", hiragana: "ゆうはん", meaning: "저녁밥" },
  { kanji: "ズボン", hiragana: "", meaning: "바지" },
  { kanji: "小さな", hiragana: "ちいさな", meaning: "작은" },
  { kanji: "同じ", hiragana: "おなじ", meaning: "같음, 통일" },
  { kanji: "お腹", hiragana: "おなか", meaning: "배" },
  { kanji: "生徒", hiragana: "せいと", meaning: "학생, 생도" },
  { kanji: "答える", hiragana: "こたえる", meaning: "대답하다" },
  { kanji: "クラス", hiragana: "", meaning: "클래스, 학급, 등급, 계급" },
  { kanji: "夜", hiragana: "よる", meaning: "밤" },
  { kanji: "電気", hiragana: "でんき", meaning: "전기" },
  { kanji: "塩", hiragana: "しお", meaning: "소금" },
  { kanji: "丸い", hiragana: "まるい", meaning: "둥글다" },
  { kanji: "ハンカチ", hiragana: "", meaning: "손수건" },
  { kanji: "遅い", hiragana: "おそい", meaning: "늦다, 느리다, 더디다" },
  { kanji: "いつも", hiragana: "", meaning: "언제나, 늘, 항상" },
  { kanji: "青い", hiragana: "あおい", meaning: "파랗다, 푸르다" },
  { kanji: "一人", hiragana: "ひとり", meaning: "한 사람, 한 명, 혼자" },
  { kanji: "眼鏡", hiragana: "めがね", meaning: "안경" },
  { kanji: "帰る", hiragana: "かえる", meaning: "돌아가다, 돌아오다" },
  { kanji: "南", hiragana: "みなみ", meaning: "남, 남쪽" },
  { kanji: "一昨年", hiragana: "おととし", meaning: "재작년" },
  { kanji: "寝る", hiragana: "ねる", meaning: "자다, 잠을 자다" },
  { kanji: "こんにちは", hiragana: "こんにちは", meaning: "안녕하세요, 낮 인사" },
  { kanji: "おじいさん", hiragana: "", meaning: "할아버지, 영감님" },
  { kanji: "喫茶店", hiragana: "きっさてん", meaning: "찻집, 다방" },
  { kanji: "話", hiragana: "はなし", meaning: "이야기, 말" },
  { kanji: "大人", hiragana: "おとな", meaning: "어른" },
  { kanji: "奥さん", hiragana: "おくさん", meaning: "부인" },
  { kanji: "千", hiragana: "せん", meaning: "천, 1000" },
  { kanji: "ゼロ", hiragana: "", meaning: "0, 제로" },
  { kanji: "多い", hiragana: "おおい", meaning: "많다" },
  { kanji: "コーヒー", hiragana: "", meaning: "커피" },
  { kanji: "家", hiragana: "いえ", meaning: "집" },
  { kanji: "雨", hiragana: "あめ", meaning: "비" },
  { kanji: "大きい", hiragana: "おおきい", meaning: "크다" },
  { kanji: "こちら", hiragana: "", meaning: "이쪽, 여기, 이곳" },
  { kanji: "十日", hiragana: "とおか", meaning: "열흘, 10일" },
  { kanji: "服", hiragana: "ふく", meaning: "옷" },
  { kanji: "夏", hiragana: "なつ", meaning: "여름" },
  { kanji: "春", hiragana: "はる", meaning: "봄" },
  { kanji: "今朝", hiragana: "けさ", meaning: "오늘 아침" },
  { kanji: "時々", hiragana: "ときどき", meaning: "때때로, 가끔" },
  { kanji: "出る", hiragana: "でる", meaning: "나가다, 나오다" },
  { kanji: "側", hiragana: "そば", meaning: "옆, 측, 곁, 쪽" },
  { kanji: "降りる", hiragana: "おりる", meaning: "내리다" },
  { kanji: "そんな", hiragana: "", meaning: "그런, 그러한, 그렇게" },
  { kanji: "カップ", hiragana: "", meaning: "컵" },
  { kanji: "口", hiragana: "くち", meaning: "입" },
  { kanji: "女の子", hiragana: "おんなのこ", meaning: "여자아이" },
  { kanji: "紙", hiragana: "かみ", meaning: "종이" },
  { kanji: "毎年", hiragana: "まいとし", meaning: "매년" },
  { kanji: "女", hiragana: "おんな", meaning: "여자" },
  { kanji: "黒い", hiragana: "くろい", meaning: "검다, 까맣다" },
  { kanji: "ご飯", hiragana: "ごはん", meaning: "밥, 식사" },
  { kanji: "傘", hiragana: "かさ", meaning: "우산" },
  { kanji: "花瓶", hiragana: "かびん", meaning: "꽃병" },
  { kanji: "誰", hiragana: "だれ", meaning: "누구" },
  { kanji: "お母さん", hiragana: "おかあさん", meaning: "어머니" },
  { kanji: "タクシー", hiragana: "", meaning: "택시" },
  { kanji: "テーブル", hiragana: "", meaning: "테이블" },
  { kanji: "右", hiragana: "みぎ", meaning: "오른쪽, 우측, 우" },
  { kanji: "靴", hiragana: "くつ", meaning: "신발, 구두" },
  { kanji: "コップ", hiragana: "", meaning: "컵" },
  { kanji: "便利", hiragana: "べんり", meaning: "편리" },
  { kanji: "出口", hiragana: "でぐち", meaning: "출구" },
  { kanji: "早い", hiragana: "はやい", meaning: "빠르다, 이르다" },
  { kanji: "撮る", hiragana: "とる", meaning: "찍다, 사진을 찍다" },
  { kanji: "犬", hiragana: "いぬ", meaning: "개" },
  { kanji: "ここ", hiragana: "", meaning: "여기, 이곳" },
  { kanji: "一", hiragana: "いち", meaning: "1, 일, 하나, 첫째" },
  { kanji: "あなた", hiragana: "", meaning: "당신, 여보" },
  { kanji: "ボタン", hiragana: "", meaning: "버튼, 단추" },
  { kanji: "遊ぶ", hiragana: "あそぶ", meaning: "놀다" },
  { kanji: "英語", hiragana: "えいご", meaning: "영어" },
  { kanji: "テレビ", hiragana: "", meaning: "텔레비전" },
  { kanji: "ドア", hiragana: "", meaning: "문, 도어" },
  { kanji: "初めまして", hiragana: "はじめまして", meaning: "처음 뵙겠습니다" },
  { kanji: "作文", hiragana: "さくぶん", meaning: "작문" },
  { kanji: "六", hiragana: "ろく", meaning: "6" },
  { kanji: "卵", hiragana: "たまご", meaning: "알, 달걀, 계란" },
  { kanji: "飲み物", hiragana: "のみもの", meaning: "마실 것, 음료" },
  { kanji: "あの", hiragana: "", meaning: "저, 그" },
  { kanji: "節倹", hiragana: "せっけん", meaning: "절약, 절검" },
  { kanji: "ゆっくり", hiragana: "", meaning: "천천히, 서서히" },
  { kanji: "下", hiragana: "した", meaning: "아래" },
  { kanji: "散歩", hiragana: "さんぽ", meaning: "산책, 산보" },
  { kanji: "仕事", hiragana: "しごと", meaning: "일, 직업, 업무" },
  { kanji: "どちら", hiragana: "", meaning: "어느 쪽" },
  { kanji: "作る", hiragana: "つくる", meaning: "만들다" },
  { kanji: "強い", hiragana: "つよい", meaning: "강하다, 세다" },
  { kanji: "嫌", hiragana: "いや", meaning: "싫음" },
  { kanji: "毎月", hiragana: "まいつき", meaning: "매월, 매달" },
  { kanji: "五", hiragana: "ご", meaning: "5" },
  { kanji: "どう", hiragana: "", meaning: "어때, 어떻게" },
  { kanji: "今月", hiragana: "こんげつ", meaning: "이달, 이번달" },
  { kanji: "ホテル", hiragana: "", meaning: "호텔" },
  { kanji: "目", hiragana: "め", meaning: "눈" },
  { kanji: "海", hiragana: "うみ", meaning: "바다" },
  { kanji: "蕎麦", hiragana: "そば", meaning: "메밀 국수" },
  { kanji: "日曜日", hiragana: "にちようび", meaning: "일요일" },
  { kanji: "いつ", hiragana: "", meaning: "언제, 어느 때" },
  { kanji: "カメラ", hiragana: "", meaning: "카메라" },
  { kanji: "少ない", hiragana: "すくない", meaning: "적다, 드물다" },
  { kanji: "料理", hiragana: "りょうり", meaning: "요리" },
  { kanji: "名前", hiragana: "なまえ", meaning: "이름" },
  { kanji: "賑やか", hiragana: "にぎやか", meaning: "활기참, 번화함" },
  { kanji: "要る", hiragana: "いる", meaning: "필요하다" },
  { kanji: "教室", hiragana: "きょうしつ", meaning: "교실" },
  { kanji: "シャツ", hiragana: "", meaning: "셔츠" },
  { kanji: "カレンダー", hiragana: "", meaning: "달력, 캘린더" },
  { kanji: "テープ", hiragana: "", meaning: "테이프" },
  { kanji: "毎朝", hiragana: "まいあさ", meaning: "매일 아침" },
  { kanji: "する", hiragana: "", meaning: "하다" },
  { kanji: "高い", hiragana: "たかい", meaning: "비싸다, 높다" },
  { kanji: "道", hiragana: "みち", meaning: "길, 도로" },
  { kanji: "勉強", hiragana: "べんきょう", meaning: "공부" },
  { kanji: "だけ", hiragana: "", meaning: "~밖에, ~만큼, ~뿐, ~만" },
  { kanji: "鼻", hiragana: "はな", meaning: "코, 후각" },
  { kanji: "昼", hiragana: "ひる", meaning: "낮" },
  { kanji: "外", hiragana: "そと", meaning: "밖, 바깥" },
  { kanji: "物", hiragana: "もの", meaning: "것, 물건" },
  { kanji: "近く", hiragana: "ちかく", meaning: "가까운 곳, 근처" },
  { kanji: "休む", hiragana: "やすむ", meaning: "쉬다" },
  { kanji: "曲がる", hiragana: "まがる", meaning: "구부러지다, 굽다, 방향을 바꾸다, 돌다" },
  { kanji: "不味い", hiragana: "まずい", meaning: "맛이 없다" },
  { kanji: "七日", hiragana: "なのか", meaning: "7일, 이레" },
  { kanji: "冬", hiragana: "ふゆ", meaning: "겨울" },
  { kanji: "兄弟", hiragana: "きょうだい", meaning: "형제" },
  { kanji: "あちら", hiragana: "", meaning: "저쪽, 저기" },
  { kanji: "困る", hiragana: "こまる", meaning: "곤란하다" },
  { kanji: "ストーブ", hiragana: "", meaning: "난로, 스토브" },
  { kanji: "横", hiragana: "よこ", meaning: "옆, 가로" },
  { kanji: "新しい", hiragana: "あたらしい", meaning: "새롭다" },
  { kanji: "ノート", hiragana: "", meaning: "노트" },
  { kanji: "夏休み", hiragana: "なつやすみ", meaning: "여름방학, 여름휴가" },
  { kanji: "食べ物", hiragana: "たべもの", meaning: "먹을 것, 음식" },
  { kanji: "どういたしまして", hiragana: "", meaning: "천만에요, 별 말씀을요" },
  { kanji: "階段", hiragana: "かいだん", meaning: "계단" },
  { kanji: "結婚", hiragana: "けっこん", meaning: "결혼" },
  { kanji: "葉書", hiragana: "はがき", meaning: "엽서" },
  { kanji: "食堂", hiragana: "しょくどう", meaning: "식당" },
  { kanji: "長い", hiragana: "ながい", meaning: "길다" },
  { kanji: "スカート", hiragana: "", meaning: "스커트, 치마" },
  { kanji: "ボールペン", hiragana: "", meaning: "볼펜" },
  { kanji: "弱い", hiragana: "よわい", meaning: "약하다" },
  { kanji: "去年", hiragana: "きょねん", meaning: "지난해, 작년" },
  { kanji: "被る", hiragana: "かぶる", meaning: "쓰다, 뒤집어쓰다, 겹치다" },
  { kanji: "私", hiragana: "わたし", meaning: "나, 저" },
  { kanji: "出す", hiragana: "だす", meaning: "내다, 내놓다, 꺼내다" },
  { kanji: "百", hiragana: "ひゃく", meaning: "백, 100" },
  { kanji: "真っ直ぐ", hiragana: "まっすぐ", meaning: "곧장, 쭉, 똑바로, 정면" },
  { kanji: "面白い", hiragana: "おもしろい", meaning: "재밌다, 재미있다" },
  { kanji: "洋服", hiragana: "ようふく", meaning: "양복" },
  { kanji: "雑誌", hiragana: "ざっし", meaning: "잡지" },
  { kanji: "お兄さん", hiragana: "おにいさん", meaning: "형, 오빠" },
  { kanji: "学校", hiragana: "がっこう", meaning: "학교" },
  { kanji: "毎日", hiragana: "まいにち", meaning: "매일, 날마다" },
  { kanji: "天気", hiragana: "てんき", meaning: "날씨" },
  { kanji: "男", hiragana: "おとこ", meaning: "남자" },
  { kanji: "おばあさん", hiragana: "", meaning: "할머니" },
  { kanji: "エレベーター", hiragana: "", meaning: "엘리베이터" },
  { kanji: "閉まる", hiragana: "しまる", meaning: "닫히다" },
  { kanji: "まだ", hiragana: "", meaning: "아직, 계속" },
  { kanji: "鉛筆", hiragana: "えんぴつ", meaning: "연필" },
  { kanji: "町", hiragana: "まち", meaning: "마을, 거리" },
  { kanji: "先週", hiragana: "せんしゅう", meaning: "지난 주, 저번 주" },
  { kanji: "学生", hiragana: "がくせい", meaning: "학생" },
  { kanji: "どうも", hiragana: "", meaning: "정말, 참, 매우, 아무래도, 어딘가, 어쩐지, 감사합니다" },
  { kanji: "何方", hiragana: "どなた", meaning: "어느 분, 누구" },
  { kanji: "低い", hiragana: "ひくい", meaning: "낮다, 작다, 얕다" },
  { kanji: "教える", hiragana: "おしえる", meaning: "가르치다" },
  { kanji: "美味しい", hiragana: "おいしい", meaning: "맛있다" },
  { kanji: "明日", hiragana: "あした", meaning: "내일" },
  { kanji: "誕生日", hiragana: "たんじょうび", meaning: "생일" },
  { kanji: "警官", hiragana: "けいかん", meaning: "경관, 경찰관" },
  { kanji: "はい", hiragana: "", meaning: "네, 예" },
  { kanji: "一時", hiragana: "いちじ", meaning: "일시, 한때, 한동안" },
  { kanji: "先生", hiragana: "せんせい", meaning: "선생님" },
  { kanji: "漢字", hiragana: "かんじ", meaning: "한자" },
  { kanji: "鍵", hiragana: "かぎ", meaning: "열쇠" },
  { kanji: "おじさん", hiragana: "", meaning: "아저씨, 백부, 숙부" },
  { kanji: "無い", hiragana: "ない", meaning: "없다" },
  { kanji: "番号", hiragana: "ばんごう", meaning: "번호" },
  { kanji: "八", hiragana: "はち", meaning: "8" },
  { kanji: "トイレ", hiragana: "", meaning: "화장실" },
  { kanji: "風邪", hiragana: "かぜ", meaning: "감기" },
  { kanji: "もしもし", hiragana: "", meaning: "여보세요" },
  { kanji: "今週", hiragana: "こんしゅう", meaning: "금주, 이번 주" },
  { kanji: "体", hiragana: "からだ", meaning: "몸, 육체, 신체" },
  { kanji: "話す", hiragana: "はなす", meaning: "말하다, 이야기하다" },
  { kanji: "いいえ", hiragana: "", meaning: "아니요, 아니" },
  { kanji: "白い", hiragana: "しろい", meaning: "하얗다, 희다" },
  { kanji: "でも", hiragana: "", meaning: "~라도, ~지라도, 하지만" },
  { kanji: "友達", hiragana: "ともだち", meaning: "친구" },
  { kanji: "軽い", hiragana: "かるい", meaning: "가볍다" },
  { kanji: "浴びる", hiragana: "あびる", meaning: "뒤집어쓰다, 샤워하다, 끼얹다" },
  { kanji: "図書館", hiragana: "としょかん", meaning: "도서관" },
  { kanji: "どの", hiragana: "", meaning: "어느, 어떤" },
  { kanji: "暑い", hiragana: "あつい", meaning: "덥다" },
  { kanji: "こんばんは", hiragana: "", meaning: "안녕하세요, 저녁 인사" },
  { kanji: "円", hiragana: "えん", meaning: "엔, 둥근 것, 원" },
  { kanji: "国", hiragana: "くに", meaning: "나라, 국가" },
  { kanji: "ちょっと", hiragana: "", meaning: "잠깐, 조금, 여보세요" },
  { kanji: "机", hiragana: "つくえ", meaning: "책상" },
  { kanji: "ギター", hiragana: "", meaning: "기타" },
  { kanji: "甘い", hiragana: "あまい", meaning: "달다, 달콤하다" },
  { kanji: "開ける", hiragana: "あける", meaning: "열다" },
  { kanji: "耳", hiragana: "みみ", meaning: "귀" },
  { kanji: "安い", hiragana: "やすい", meaning: "싸다, 편하다" },
  { kanji: "古い", hiragana: "ふるい", meaning: "오래되다, 낡다" },
  { kanji: "時計", hiragana: "とけい", meaning: "시계" },
  { kanji: "テスト", hiragana: "", meaning: "테스트" },
  { kanji: "会う", hiragana: "あう", meaning: "만나다, 대면하다" },
  { kanji: "あそこ", hiragana: "", meaning: "저기, 저곳" },
  { kanji: "電車", hiragana: "でんしゃ", meaning: "전차, 전철" },
  { kanji: "雪", hiragana: "ゆき", meaning: "눈" },
  { kanji: "好き", hiragana: "すき", meaning: "좋아하다" },
  { kanji: "歩く", hiragana: "あるく", meaning: "걷다" },
  { kanji: "土曜日", hiragana: "どようび", meaning: "토요일" },
  { kanji: "来週", hiragana: "らいしゅう", meaning: "다음 주" },
  { kanji: "辛い", hiragana: "からい", meaning: "맵다" },
  { kanji: "少し", hiragana: "すこし", meaning: "조금, 약간, 좀" },
  { kanji: "デパート", hiragana: "", meaning: "백화점" },
  { kanji: "鞄", hiragana: "かばん", meaning: "가방" },
  { kanji: "外国人", hiragana: "がいこくじん", meaning: "외국인" },
  { kanji: "地下鉄", hiragana: "ちかてつ", meaning: "지하철" },
  { kanji: "先月", hiragana: "せんげつ", meaning: "저번 달, 지난 달" },
  { kanji: "見せる", hiragana: "みせる", meaning: "보여주다" },
  { kanji: "財布", hiragana: "さいふ", meaning: "지갑" },
  { kanji: "其方", hiragana: "そちら", meaning: "그쪽" },
  { kanji: "お金", hiragana: "おかね", meaning: "돈, 금전" },
  { kanji: "使う", hiragana: "つかう", meaning: "쓰다, 사용하다, 소비하다" },
  { kanji: "黄色い", hiragana: "きいろい", meaning: "노랗다" },
  { kanji: "午前", hiragana: "ごぜん", meaning: "오전" },
  { kanji: "後", hiragana: "あと", meaning: "뒤, 다음, 후, 나중에" },
  { kanji: "乗る", hiragana: "のる", meaning: "타다, 오르다" },
  { kanji: "台所", hiragana: "だいどころ", meaning: "부엌" },
  { kanji: "大丈夫", hiragana: "だいじょうぶ", meaning: "괜찮음, 걱정없음" },
  { kanji: "東", hiragana: "ひがし", meaning: "동쪽, 동" },
  { kanji: "今晩", hiragana: "こんばん", meaning: "오늘 밤" },
  { kanji: "猫", hiragana: "ねこ", meaning: "고양이" },
  { kanji: "生まれる", hiragana: "うまれる", meaning: "태어나다, 생기다, 발생하다" },
  { kanji: "入口", hiragana: "いりぐち", meaning: "입구" },
  { kanji: "後ろ", hiragana: "うしろ", meaning: "뒤, 뒤쪽" },
  { kanji: "火曜日", hiragana: "かようび", meaning: "화요일" },
  { kanji: "今年", hiragana: "ことし", meaning: "올해, 금년" },
  { kanji: "吸う", hiragana: "すう", meaning: "들이마시다, 빨아들이다, 담배를 피다" },
  { kanji: "父", hiragana: "ちち", meaning: "아버지" },
  { kanji: "公園", hiragana: "こうえん", meaning: "공원" },
  { kanji: "動物", hiragana: "どうぶつ", meaning: "동물" },
  { kanji: "ラジオ", hiragana: "", meaning: "라디오" },
  { kanji: "あんな", hiragana: "", meaning: "저런, 저러한" },
  { kanji: "さようなら", hiragana: "", meaning: "안녕, 안녕히 가세요" },
  { kanji: "コート", hiragana: "", meaning: "코트" },
  { kanji: "写真", hiragana: "しゃしん", meaning: "사진" },
  { kanji: "どうぞ", hiragana: "", meaning: "아무쪼록, 부디, 그럼" },
  { kanji: "閉める", hiragana: "しめる", meaning: "닫다" },
  { kanji: "飛行機", hiragana: "ひこうき", meaning: "비행기" },
  { kanji: "押す", hiragana: "おす", meaning: "밀다, 누르다" },
  { kanji: "シャワー", hiragana: "", meaning: "샤워, 목욕" },
  { kanji: "すみません", hiragana: "", meaning: "실례합니다, 죄송합니다" },
  { kanji: "ペン", hiragana: "", meaning: "펜" },
  { kanji: "駅", hiragana: "えき", meaning: "역, 정거장" },
  { kanji: "読む", hiragana: "よむ", meaning: "읽다" },
  { kanji: "午後", hiragana: "ごご", meaning: "오후" },
  { kanji: "三日", hiragana: "みっか", meaning: "사흘, 3일" },
  { kanji: "位", hiragana: "くらい", meaning: "정도, 만큼, 따위, 지위" },
  { kanji: "姉", hiragana: "あね", meaning: "누나, 언니" },
  { kanji: "色", hiragana: "いろ", meaning: "색, 색채" },
  { kanji: "電話", hiragana: "でんわ", meaning: "전화" },
  { kanji: "石鹸", hiragana: "せっけん", meaning: "비누" },
  { kanji: "磨く", hiragana: "みがく", meaning: "닦다, 윤내다, 연마하다" },
  { kanji: "交番", hiragana: "こうばん", meaning: "파출소" },
  { kanji: "これ", hiragana: "", meaning: "이것, 이" },
  { kanji: "上手", hiragana: "じょうず", meaning: "능숙, 잘함" },
  { kanji: "会社", hiragana: "かいしゃ", meaning: "회사" },
  { kanji: "窓", hiragana: "まど", meaning: "창, 창문" },
  { kanji: "その", hiragana: "", meaning: "그, 저" },
  { kanji: "可愛い", hiragana: "かわいい", meaning: "귀엽다, 사랑스럽다" },
  { kanji: "五日", hiragana: "いつか", meaning: "닷새, 5일" },
  { kanji: "八日", hiragana: "ようか", meaning: "여드레, 8일" },
  { kanji: "入れる", hiragana: "いれる", meaning: "넣다" },
  { kanji: "木", hiragana: "き", meaning: "나무" },
  { kanji: "北", hiragana: "きた", meaning: "북쪽, 북" },
  { kanji: "どれ", hiragana: "", meaning: "어느 것, 어떤 것" },
  { kanji: "また", hiragana: "", meaning: "또, 다시, 그리고" },
  { kanji: "咲く", hiragana: "さく", meaning: "피다, 꽃이 피다" },
  { kanji: "もっと", hiragana: "", meaning: "좀 더, 더, 더욱" },
  { kanji: "前", hiragana: "まえ", meaning: "앞, 이전, 먼저" },
  { kanji: "人", hiragana: "ひと", meaning: "사람" },
  { kanji: "歌う", hiragana: "うたう", meaning: "노래를 부르다, 노래하다" },
  { kanji: "鳥肉", hiragana: "とりにく", meaning: "닭고기" },
  { kanji: "朝", hiragana: "あさ", meaning: "아침" },
  { kanji: "登る", hiragana: "のぼる", meaning: "오르다, 올라가다" },
  { kanji: "見る", hiragana: "みる", meaning: "보다" },
  { kanji: "暗い", hiragana: "くらい", meaning: "어둡다" },
  { kanji: "短い", hiragana: "みじかい", meaning: "짧다" },
  { kanji: "いる", hiragana: "", meaning: "있다, (생물) 있다" },
  { kanji: "とても", hiragana: "", meaning: "매우, 대단히" },
  { kanji: "来年", hiragana: "らいねん", meaning: "내년" },
  { kanji: "返す", hiragana: "かえす", meaning: "되돌리다, 돌려주다, 갚다" },
  { kanji: "辞書", hiragana: "じしょ", meaning: "사전" },
  { kanji: "掛かる", hiragana: "かかる", meaning: "걸리다, 들다, 매달리다" },
  { kanji: "方", hiragana: "ほう", meaning: "방면, 방향, 편, 쪽" },
  { kanji: "グラス", hiragana: "", meaning: "글라스, 유리컵" },
  { kanji: "二十日", hiragana: "はつか", meaning: "20일" },
  { kanji: "食べる", hiragana: "たべる", meaning: "먹다" },
  { kanji: "書く", hiragana: "かく", meaning: "쓰다" },
  { kanji: "隣", hiragana: "となり", meaning: "이웃, 옆" },
  { kanji: "音楽", hiragana: "おんがく", meaning: "음악" },
  { kanji: "元気", hiragana: "げんき", meaning: "원기, 기력, 건강함" },
  { kanji: "今", hiragana: "いま", meaning: "지금, 이제, 현재" },
  { kanji: "明後日", hiragana: "あさって", meaning: "모레" },
  { kanji: "部屋", hiragana: "へや", meaning: "방" },
  { kanji: "大好き", hiragana: "だいすき", meaning: "매우 좋아하다, 사랑하다" },
  { kanji: "どうして", hiragana: "", meaning: "어째서, 왜" },
  { kanji: "洗う", hiragana: "あらう", meaning: "씻다" },
  { kanji: "一日", hiragana: "ついたち", meaning: "1일, 초하루" },
  { kanji: "呼ぶ", hiragana: "よぶ", meaning: "부르다" },
  { kanji: "こんな", hiragana: "", meaning: "이러한, 이와 같은, 이런" },
  { kanji: "皆さん", hiragana: "みなさん", meaning: "여러분" },
  { kanji: "覚える", hiragana: "おぼえる", meaning: "기억하다, 외우다, 배우다, 느끼다" },
  { kanji: "三", hiragana: "さん", meaning: "3" },
  { kanji: "綺麗", hiragana: "きれい", meaning: "고움, 예쁨, 깨끗함" },
  { kanji: "五つ", hiragana: "いつつ", meaning: "5개, 다섯" },
  { kanji: "それ", hiragana: "", meaning: "그것" },
  { kanji: "空", hiragana: "そら", meaning: "하늘" },
  { kanji: "暇", hiragana: "ひま", meaning: "한가한, 여유로운, 틈, 짬" },
  { kanji: "医者", hiragana: "いしゃ", meaning: "의사" },
  { kanji: "なぜ", hiragana: "", meaning: "왜, 어째서" },
  { kanji: "赤い", hiragana: "あかい", meaning: "붉다, 빨강, 빨갛다" },
  { kanji: "速い", hiragana: "はやい", meaning: "빠르다" },
  { kanji: "良い", hiragana: "よい", meaning: "좋다, 뛰어나다" },
  { kanji: "二", hiragana: "に", meaning: "2" },
  { kanji: "貸す", hiragana: "かす", meaning: "빌려주다" },
  { kanji: "九", hiragana: "きゅう", meaning: "9" },
  { kanji: "角", hiragana: "かど", meaning: "귀퉁이, 구석, 모퉁이, 모서리" },
  { kanji: "頭", hiragana: "あたま", meaning: "머리" },
  { kanji: "八百屋", hiragana: "やおや", meaning: "야채 가게" },
  { kanji: "どこ", hiragana: "", meaning: "어디" },
  { kanji: "段々", hiragana: "だんだん", meaning: "차차, 점점" },
  { kanji: "男の子", hiragana: "おとこのこ", meaning: "남자아이" },
  { kanji: "中", hiragana: "なか", meaning: "가운데, 안, 중, 속" },
  { kanji: "難しい", hiragana: "むずかしい", meaning: "어렵다" },
  { kanji: "遠い", hiragana: "とおい", meaning: "멀다, 친하지 않다, 소원하다" },
  { kanji: "スポーツ", hiragana: "", meaning: "스포츠" },
  { kanji: "肉", hiragana: "にく", meaning: "고기" },
  { kanji: "四日", hiragana: "よっか", meaning: "4일, 나흘" },
  { kanji: "忙しい", hiragana: "いそがしい", meaning: "바쁘다" },
  { kanji: "大学", hiragana: "だいがく", meaning: "대학, 대학교" },
  { kanji: "兄", hiragana: "あに", meaning: "형, 오빠" },
  { kanji: "ネクタイ", hiragana: "", meaning: "넥타이" },
  { kanji: "来月", hiragana: "らいげつ", meaning: "다음 달" },
];