// lib/words_26_30.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_26_30: Word[] = [
  { kanji: "外国人", hiragana: "がいこくじん", meaning: "외국인" },
  { kanji: "地下鉄", hiragana: "ちかてつ", meaning: "지하철" },
  { kanji: "先月", hiragana: "せんげつ", meaning: "저번 달, 지난 달" },
  { kanji: "見せる", hiragana: "みせる", meaning: "보여주다" },
  { kanji: "財布", hiragana: "さいふ", meaning: "지갑" },
  { kanji: "其方", hiragana: "そちら", meaning: "그쪽" },
  { kanji: "お金", hiragana: "おかね", meaning: "돈, 금전" },
  { kanji: "使う", hiragana: "つかう", meaning: "쓰다, 사용하다, 소비하다" },
  { kanji: "黄色い", hiragana: "きいろい", meaning: "노랗다" },
  { kanji: "午前", hiragana: "ごぜん", meaning: "오전" },
  { kanji: "後", hiragana: "あと", meaning: "뒤, 다음, 후, 나중에" },
  { kanji: "乗る", hiragana: "のる", meaning: "타다, 오르다" },
  { kanji: "台所", hiragana: "だいどころ", meaning: "부엌" },
  { kanji: "大丈夫", hiragana: "だいじょうぶ", meaning: "괜찮음, 걱정없음" },
  { kanji: "東", hiragana: "ひがし", meaning: "동쪽, 동" },
  { kanji: "会話", hiragana: "かいわ", meaning: "회화" },
  { kanji: "洗い物をする", hiragana: "あらいものをする", meaning: "설거지를 하다, 설거지하다" },
  { kanji: "出勤", hiragana: "しゅっきん", meaning: "출근" },
  { kanji: "洗う", hiragana: "あらう", meaning: "씻다, 밀려왔다 나갔다 하다, 자세히 들춰 조사하다" },
  { kanji: "以来", hiragana: "いらい", meaning: "이래, 이후, 금후" },
  { kanji: "笑顔", hiragana: "えがお", meaning: "웃는 얼굴, 웃음 띤 얼굴" },
  { kanji: "任せる", hiragana: "まかせる", meaning: "맡기다, 위임하다" },
  { kanji: "懐", hiragana: "ふところ", meaning: "품, 호주머니" },
  { kanji: "箱", hiragana: "はこ", meaning: "상자" },
  { kanji: "付ける", hiragana: "つける", meaning: "붙이다, 달다" },
  { kanji: "九時", hiragana: "くじ", meaning: "9시" },
  { kanji: "開門", hiragana: "かいもん", meaning: "문을 엶, 개문" },
  { kanji: "残る", hiragana: "のこる", meaning: "남다, 머무르다, 여분이 생기다" },
  { kanji: "馬", hiragana: "うま", meaning: "말" },
  { kanji: "今晩", hiragana: "こんばん", meaning: "오늘 밤" },
  { kanji: "猫", hiragana: "ねこ", meaning: "고양이" },
  { kanji: "生まれる", hiragana: "うまれる", meaning: "태어나다, 생기다, 발생하다" },
  { kanji: "入口", hiragana: "いりぐち", meaning: "입구" },
  { kanji: "後ろ", hiragana: "うしろ", meaning: "뒤, 뒤쪽" },
  { kanji: "火曜日", hiragana: "かようび", meaning: "화요일" },
  { kanji: "今年", hiragana: "ことし", meaning: "올해, 금년" },
  { kanji: "吸う", hiragana: "すう", meaning: "들이마시다, 빨아들이다, 담배를 피다" },
  { kanji: "父", hiragana: "ちち", meaning: "아빠, 아버지" },
  { kanji: "公園", hiragana: "こうえん", meaning: "공원" },
  { kanji: "動物", hiragana: "どうぶつ", meaning: "동물" },
  { kanji: "ラジオ", hiragana: "", meaning: "라디오" },
  { kanji: "あんな", hiragana: "", meaning: "저런, 저러한" },
  { kanji: "さようなら", hiragana: "", meaning: "안녕, 안녕히 가세요" },
  { kanji: "コート", hiragana: "", meaning: "코트" },
  { kanji: "宜しい", hiragana: "よろしい", meaning: "좋다, よい의 겸양어" },
  { kanji: "膝", hiragana: "ひざ", meaning: "무릎, 대퇴부" },
  { kanji: "失う", hiragana: "うしなう", meaning: "잃다, 여의다, 잃어버리다" },
  { kanji: "赤ちゃん", hiragana: "あかちゃん", meaning: "아기, 새끼" },
  { kanji: "一回り", hiragana: "ひとまわり", meaning: "일주, 한 바퀴 돎" },
  { kanji: "行列", hiragana: "ぎょうれつ", meaning: "행렬, 줄을 섬" },
  { kanji: "生物", hiragana: "せいぶつ", meaning: "생물" },
  { kanji: "出来る", hiragana: "できる", meaning: "할 수 있다, 가능하다, 생기다, 되다" },
  { kanji: "植物", hiragana: "しょくぶつ", meaning: "식물" },
  { kanji: "落ちる", hiragana: "おちる", meaning: "떨어지다, 낙하하다" },
  { kanji: "思う", hiragana: "おもう", meaning: "생각하다" },
  { kanji: "面接", hiragana: "めんせつ", meaning: "면접" },
  { kanji: "別れる", hiragana: "わかれる", meaning: "헤어지다, 작별하다" },
  { kanji: "頂く", hiragana: "いただく", meaning: "받들다, 모시다, もらう의 겸양어" },
  { kanji: "勝利", hiragana: "しょうり", meaning: "승리" },
  { kanji: "得る", hiragana: "える", meaning: "얻다, 손에 넣다" },
  { kanji: "空気", hiragana: "くうき", meaning: "공기, 대기, 분위기" },
  { kanji: "写真", hiragana: "しゃしん", meaning: "사진" },
  { kanji: "どうぞ", hiragana: "", meaning: "아무쪼록, 부디, 그럼" },
  { kanji: "閉める", hiragana: "しめる", meaning: "닫다" },
  { kanji: "飛行機", hiragana: "ひこうき", meaning: "비행기" },
  { kanji: "押す", hiragana: "おす", meaning: "밀다, 누르다" },
  { kanji: "シャワー", hiragana: "", meaning: "샤워, 목욕" },
  { kanji: "すみません", hiragana: "", meaning: "실례합니다, 죄송합니다" },
  { kanji: "ペン", hiragana: "", meaning: "펜" },
  { kanji: "駅", hiragana: "えき", meaning: "역" },
  { kanji: "読む", hiragana: "よむ", meaning: "읽다" },
  { kanji: "午後", hiragana: "ごご", meaning: "오후" },
  { kanji: "三日", hiragana: "みっか", meaning: "사흘, 3일" },
  { kanji: "位", hiragana: "くらい", meaning: "정도, 만큼, 따위, 지위" },
  { kanji: "姉", hiragana: "あね", meaning: "누나, 언니" },
  { kanji: "色", hiragana: "いろ", meaning: "색, 색채" },
  { kanji: "本社", hiragana: "ほんしゃ", meaning: "본사" },
  { kanji: "道筋", hiragana: "みちすじ", meaning: "지나가는 길, 경로" },
  { kanji: "電送", hiragana: "でんそう", meaning: "전송" },
  { kanji: "暇", hiragana: "ひま", meaning: "틈, 짬, 한가한 상태" },
  { kanji: "扉", hiragana: "とびら", meaning: "문짝, 속표지" },
  { kanji: "吹き出す", hiragana: "ふきだす", meaning: "불기 시작하다" },
  { kanji: "鉄", hiragana: "てつ", meaning: "철, 쇠" },
  { kanji: "発病", hiragana: "はつびょう", meaning: "발병" },
  { kanji: "雲", hiragana: "くも", meaning: "구름" },
  { kanji: "帽子", hiragana: "ぼうし", meaning: "모자" },
  { kanji: "実行", hiragana: "じっこう", meaning: "실행" },
  { kanji: "気分", hiragana: "きぶん", meaning: "기분" },
  { kanji: "爽快", hiragana: "そうかい", meaning: "상쾌함, 산뜻하고 기분이 좋은 것" },
  { kanji: "毎度", hiragana: "まいど", meaning: "매번, 항상, 번번이" },
  { kanji: "手数", hiragana: "てすう", meaning: "수고" },
  { kanji: "専用", hiragana: "せんよう", meaning: "전용" },
  { kanji: "電話", hiragana: "でんわ", meaning: "전화" },
  { kanji: "石鹸", hiragana: "せっけん", meaning: "비누" },
  { kanji: "磨く", hiragana: "みがく", meaning: "닦다, 윤내다, 연마하다" },
  { kanji: "交番", hiragana: "こうばん", meaning: "파출소" },
  { kanji: "これ", hiragana: "", meaning: "이것, 이" },
  { kanji: "上手", hiragana: "じょうず", meaning: "능숙, 잘함" },
  { kanji: "会社", hiragana: "かいしゃ", meaning: "회사" },
  { kanji: "窓", hiragana: "まど", meaning: "창, 창문" },
  { kanji: "その", hiragana: "", meaning: "그, 저" },
  { kanji: "可愛い", hiragana: "かわいい", meaning: "귀엽다, 사랑스럽다" },
  { kanji: "五日", hiragana: "いつか", meaning: "닷새, 5일" },
  { kanji: "八日", hiragana: "ようか", meaning: "여드레, 8일" },
  { kanji: "入れる", hiragana: "いれる", meaning: "넣다" },
  { kanji: "木", hiragana: "き", meaning: "나무" },
  { kanji: "北", hiragana: "きた", meaning: "북쪽, 북" },
  { kanji: "故障", hiragana: "こしょう", meaning: "고장, 지장" },
  { kanji: "進路", hiragana: "しんろ", meaning: "진로" },
  { kanji: "泡立つ", hiragana: "あわだつ", meaning: "거품이 일다" },
  { kanji: "振る", hiragana: "ふる", meaning: "흔들다, 흔들어 움직이다" },
  { kanji: "初め", hiragana: "はじめ", meaning: "처음" },
  { kanji: "同僚", hiragana: "どうりょう", meaning: "동료" },
  { kanji: "一緒", hiragana: "いっしょ", meaning: "함께함, 같이함" },
  { kanji: "全開", hiragana: "ぜんかい", meaning: "전개, 전부 열어놓음" },
  { kanji: "自然", hiragana: "しぜん", meaning: "자연" },
  { kanji: "印象", hiragana: "いんしょう", meaning: "인상" },
  { kanji: "演出", hiragana: "えんしゅつ", meaning: "연출" },
  { kanji: "先発", hiragana: "せんぱつ", meaning: "선발" },
  { kanji: "出発", hiragana: "しゅっぱつ", meaning: "출발" },
  { kanji: "どれ", hiragana: "", meaning: "어느 것, 어떤 것" },
  { kanji: "また", hiragana: "", meaning: "또, 다시, 그리고" },
  { kanji: "咲く", hiragana: "さく", meaning: "피다" },
  { kanji: "もっと", hiragana: "", meaning: "좀 더, 더, 더욱" },
  { kanji: "前", hiragana: "まえ", meaning: "앞, 이전, 먼저" },
  { kanji: "人", hiragana: "ひと", meaning: "사람" },
  { kanji: "歌う", hiragana: "うたう", meaning: "노래를 부르다, 노래하다" },
  { kanji: "鳥肉", hiragana: "とりにく", meaning: "닭고기" },
  { kanji: "朝", hiragana: "あさ", meaning: "아침" },
  { kanji: "登る", hiragana: "のぼる", meaning: "오르다, 올라가다" },
  { kanji: "見る", hiragana: "みる", meaning: "보다" },
  { kanji: "暗い", hiragana: "くらい", meaning: "어둡다" },
  { kanji: "短い", hiragana: "みじかい", meaning: "짧다" },
  { kanji: "いる", hiragana: "", meaning: "있다" },
  { kanji: "とても", hiragana: "", meaning: "매우, 대단히" },
  { kanji: "本物", hiragana: "ほんもの", meaning: "진짜" },
  { kanji: "力強い", hiragana: "ちからづよい", meaning: "마음 든든하다, 안심이 되다" },
  { kanji: "伺う", hiragana: "うかがう", meaning: "찾다, 방문하다, (겸양어)" },
  { kanji: "梅", hiragana: "うめ", meaning: "매화나무, 매실" },
  { kanji: "流暢だ", hiragana: "りゅうちょうだ", meaning: "유창하다" },
  { kanji: "声", hiragana: "こえ", meaning: "목소리" },
  { kanji: "頂上", hiragana: "ちょうじょう", meaning: "정상, 꼭대기" },
  { kanji: "目掛ける", hiragana: "めがける", meaning: "목표로 하다, 노리다" },
  { kanji: "寝室", hiragana: "しんしつ", meaning: "침실" },
  { kanji: "向き", hiragana: "むき", meaning: "방향, 향하는 쪽" },
  { kanji: "幅", hiragana: "はば", meaning: "폭, 너비" },
  { kanji: "十分", hiragana: "じゅうぶん", meaning: "충분함, 충분" },
  { kanji: "長さ", hiragana: "ながさ", meaning: "길이" },
];