// lib/words_21_25.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_21_25: Word[] = [
  { kanji: "百", hiragana: "ひゃく", meaning: "백, 100" },
  { kanji: "真っ直ぐ", hiragana: "まっすぐ", meaning: "곧장, 쭉, 똑바로, 정면" },
  { kanji: "面白い", hiragana: "おもしろい", meaning: "재밌다, 재미있다" },
  { kanji: "洋服", hiragana: "ようふく", meaning: "양복" },
  { kanji: "雑誌", hiragana: "ざっし", meaning: "잡지" },
  { kanji: "お兄さん", hiragana: "おにいさん", meaning: "형, 오빠" },
  { kanji: "学校", hiragana: "がっこう", meaning: "학교" },
  { kanji: "毎日", hiragana: "まいにち", meaning: "매일, 날마다" },
  { kanji: "天気", hiragana: "てんき", meaning: "날씨" },
  { kanji: "男", hiragana: "おとこ", meaning: "남자" },
  { kanji: "おばあさん", hiragana: "", meaning: "할머니" },
  { kanji: "エレベーター", hiragana: "", meaning: "엘리베이터" },
  { kanji: "閉まる", hiragana: "しまる", meaning: "닫히다" },
  { kanji: "まだ", hiragana: "", meaning: "아직, 계속" },
  { kanji: "鉛筆", hiragana: "えんぴつ", meaning: "연필" },
  { kanji: "町", hiragana: "まち", meaning: "마을, 거리" },
  { kanji: "先週", hiragana: "せんしゅう", meaning: "지난 주, 저번 주" },
  { kanji: "学生", hiragana: "がくせい", meaning: "학생" },
  { kanji: "どうも", hiragana: "", meaning: "정말, 참, 매우, 아무래도, 어딘가, 어쩐지, 감사합니다" },
  { kanji: "何方", hiragana: "どなた", meaning: "어느 분, 누구" },
  { kanji: "低い", hiragana: "ひくい", meaning: "낮다, 작다, 얕다" },
  { kanji: "教える", hiragana: "おしえる", meaning: "가르치다" },
  { kanji: "美味しい", hiragana: "おいしい", meaning: "맛있다" },
  { kanji: "明日", hiragana: "あした", meaning: "내일" },
  { kanji: "誕生日", hiragana: "たんじょうび", meaning: "생일" },
  { kanji: "警官", hiragana: "けいかん", meaning: "경관, 경찰관" },
  { kanji: "はい", hiragana: "", meaning: "네, 예" },
  { kanji: "一時", hiragana: "いちじ", meaning: "일시, 한때, 한동안" },
  { kanji: "先生", hiragana: "せんせい", meaning: "선생님" },
  { kanji: "漢字", hiragana: "かんじ", meaning: "한자" },
  { kanji: "鍵", hiragana: "かぎ", meaning: "열쇠" },
  { kanji: "おじさん", hiragana: "", meaning: "아저씨, 백부, 숙부" },
  { kanji: "無い", hiragana: "ない", meaning: "없다" },
  { kanji: "番号", hiragana: "ばんごう", meaning: "번호" },
  { kanji: "八", hiragana: "はち", meaning: "8" },
  { kanji: "トイレ", hiragana: "", meaning: "화장실" },
  { kanji: "風邪", hiragana: "かぜ", meaning: "감기" },
  { kanji: "もしもし", hiragana: "", meaning: "여보세요" },
  { kanji: "今週", hiragana: "こんしゅう", meaning: "금주, 이번 주" },
  { kanji: "体", hiragana: "からだ", meaning: "몸, 육체, 신체" },
  { kanji: "話す", hiragana: "はなす", meaning: "말하다, 이야기하다" },
  { kanji: "いいえ", hiragana: "", meaning: "아니요, 아니" },
  { kanji: "白い", hiragana: "しろい", meaning: "하얗다, 희다" },
  { kanji: "でも", hiragana: "", meaning: "~라도, ~지라도, 하지만" },
  { kanji: "友達", hiragana: "ともだち", meaning: "친구" },
  { kanji: "軽い", hiragana: "かるい", meaning: "가볍다" },
  { kanji: "浴びる", hiragana: "あびる", meaning: "뒤집어쓰다, 샤워하다, 끼얹다" },
  { kanji: "図書館", hiragana: "としょかん", meaning: "도서관" },
  { kanji: "どの", hiragana: "", meaning: "어느, 어떤" },
  { kanji: "暑い", hiragana: "あつい", meaning: "덥다" },
  { kanji: "こんばんは", hiragana: "", meaning: "안녕하세요, 저녁 인사" },
  { kanji: "円", hiragana: "えん", meaning: "엔, 둥근 것, 원" },
  { kanji: "国", hiragana: "くに", meaning: "나라, 국가" },
  { kanji: "ちょっと", hiragana: "", meaning: "잠깐, 조금, 여보세요" },
  { kanji: "机", hiragana: "つくえ", meaning: "책상" },
  { kanji: "ギター", hiragana: "", meaning: "기타" },
  { kanji: "甘い", hiragana: "あまい", meaning: "달다, 달콤하다" },
  { kanji: "開ける", hiragana: "あける", meaning: "열다" },
  { kanji: "耳", hiragana: "みみ", meaning: "귀" },
  { kanji: "安い", hiragana: "やすい", meaning: "싸다, 편하다" },
  { kanji: "古い", hiragana: "ふるい", meaning: "오래되다, 낡다" },
  { kanji: "時計", hiragana: "とけい", meaning: "시계" },
  { kanji: "テスト", hiragana: "", meaning: "테스트" },
  { kanji: "会う", hiragana: "あう", meaning: "만나다, 대면하다" },
  { kanji: "あそこ", hiragana: "", meaning: "저기, 저곳" },
  { kanji: "電車", hiragana: "でんしゃ", meaning: "전차, 전철" },
  { kanji: "雪", hiragana: "ゆき", meaning: "눈" },
  { kanji: "好き", hiragana: "すき", meaning: "좋아하다" },
  { kanji: "歩く", hiragana: "あるく", meaning: "걷다" },
  { kanji: "土曜日", hiragana: "どようび", meaning: "토요일" },
  { kanji: "来週", hiragana: "らいしゅう", meaning: "다음 주" },
  { kanji: "辛い", hiragana: "からい", meaning: "맵다" },
  { kanji: "少し", hiragana: "すこし", meaning: "조금, 약간, 좀" },
  { kanji: "デパート", hiragana: "", meaning: "백화점" },
  { kanji: "鞄", hiragana: "かばん", meaning: "가방" },
];
