// lib/words_11_15.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_11_15: Word[] = [
  { kanji: "四", hiragana: "し, よん", meaning: "4" },
  { kanji: "夕飯", hiragana: "ゆうはん", meaning: "저녁밥" },
  { kanji: "ズボン", hiragana: "", meaning: "바지" },
  { kanji: "小さな", hiragana: "ちいさな", meaning: "작은" },
  { kanji: "同じ", hiragana: "おなじ", meaning: "같음, 통일" },
  { kanji: "お腹", hiragana: "おなか", meaning: "배" },
  { kanji: "生徒", hiragana: "せいと", meaning: "학생, 생도" },
  { kanji: "答える", hiragana: "こたえる", meaning: "대답하다" },
  { kanji: "クラス", hiragana: "", meaning: "클래스, 학급, 등급, 계급" },
  { kanji: "夜", hiragana: "よる", meaning: "밤" },
  { kanji: "電気", hiragana: "でんき", meaning: "전기" },
  { kanji: "塩", hiragana: "しお", meaning: "소금" },
  { kanji: "丸い", hiragana: "まるい", meaning: "둥글다" },
  { kanji: "ハンカチ", hiragana: "", meaning: "손수건" },
  { kanji: "遅い", hiragana: "おそい", meaning: "늦다, 느리다, 더디다" },
  { kanji: "いつも", hiragana: "", meaning: "언제나, 늘, 항상" },
  { kanji: "青い", hiragana: "あおい", meaning: "파랗다, 푸르다" },
  { kanji: "一人", hiragana: "ひとり", meaning: "한 사람, 한 명, 혼자" },
  { kanji: "眼鏡", hiragana: "めがね", meaning: "안경" },
  { kanji: "帰る", hiragana: "かえる", meaning: "돌아가다, 돌아오다" },
  { kanji: "南", hiragana: "みなみ", meaning: "남, 남쪽" },
  { kanji: "一昨年", hiragana: "おととし", meaning: "재작년" },
  { kanji: "寝る", hiragana: "ねる", meaning: "자다, 잠을 자다" },
  { kanji: "こんにちは", hiragana: "こんにちは", meaning: "안녕하세요, 낮 인사" },
  { kanji: "おじいさん", hiragana: "", meaning: "할아버지, 영감님" },
  { kanji: "喫茶店", hiragana: "きっさてん", meaning: "찻집, 다방" },
  { kanji: "話", hiragana: "はなし", meaning: "이야기, 말" },
  { kanji: "大人", hiragana: "おとな", meaning: "어른" },
  { kanji: "奥さん", hiragana: "おくさん", meaning: "부인" },
  { kanji: "千", hiragana: "せん", meaning: "천, 1000" },
  { kanji: "ゼロ", hiragana: "", meaning: "0, 제로" },
  { kanji: "多い", hiragana: "おおい", meaning: "많다" },
  { kanji: "コーヒー", hiragana: "", meaning: "커피" },
  { kanji: "家", hiragana: "いえ", meaning: "집" },
  { kanji: "雨", hiragana: "あめ", meaning: "비" },
  { kanji: "大きい", hiragana: "おおきい", meaning: "크다" },
  { kanji: "こちら", hiragana: "", meaning: "이쪽, 여기, 이곳" },
  { kanji: "十日", hiragana: "とおか", meaning: "열흘, 10일" },
  { kanji: "服", hiragana: "ふく", meaning: "옷" },
  { kanji: "夏", hiragana: "なつ", meaning: "여름" },
  { kanji: "春", hiragana: "はる", meaning: "봄" },
  { kanji: "今朝", hiragana: "けさ", meaning: "오늘 아침" },
  { kanji: "時々", hiragana: "ときどき", meaning: "때때로, 가끔" },
  { kanji: "出る", hiragana: "でる", meaning: "나가다, 나오다" },
  { kanji: "側", hiragana: "そば", meaning: "옆, 측, 곁, 쪽" },
  { kanji: "降りる", hiragana: "おりる", meaning: "내리다" },
  { kanji: "そんな", hiragana: "", meaning: "그런, 그러한, 그렇게" },
  { kanji: "カップ", hiragana: "", meaning: "컵" },
  { kanji: "口", hiragana: "くち", meaning: "입" },
  { kanji: "女の子", hiragana: "おんなのこ", meaning: "여자아이" },
  { kanji: "紙", hiragana: "かみ", meaning: "종이" },
  { kanji: "毎年", hiragana: "まいとし", meaning: "매년" },
  { kanji: "女", hiragana: "おんな", meaning: "여자" },
  { kanji: "黒い", hiragana: "くろい", meaning: "검다, 까맣다" },
  { kanji: "ご飯", hiragana: "ごはん", meaning: "밥, 식사" },
  { kanji: "傘", hiragana: "かさ", meaning: "우산" },
  { kanji: "花瓶", hiragana: "かびん", meaning: "꽃병" },
  { kanji: "誰", hiragana: "だれ", meaning: "누구" },
  { kanji: "お母さん", hiragana: "おかあさん", meaning: "어머니" },
  { kanji: "タクシー", hiragana: "", meaning: "택시" },
  { kanji: "テーブル", hiragana: "", meaning: "테이블" },
  { kanji: "右", hiragana: "みぎ", meaning: "오른쪽, 우측, 우" },
  { kanji: "靴", hiragana: "くつ", meaning: "신발, 구두" },
  { kanji: "コップ", hiragana: "", meaning: "컵" },
  { kanji: "便利", hiragana: "べんり", meaning: "편리" },
  { kanji: "出口", hiragana: "でぐち", meaning: "출구" },
  { kanji: "早い", hiragana: "はやい", meaning: "빠르다, 이르다" },
  { kanji: "撮る", hiragana: "とる", meaning: "찍다, 사진을 찍다" },
  { kanji: "犬", hiragana: "いぬ", meaning: "개" },
  { kanji: "ここ", hiragana: "", meaning: "여기, 이곳" },
  { kanji: "一", hiragana: "いち", meaning: "1, 일, 하나, 첫째" },
  { kanji: "あなた", hiragana: "", meaning: "당신, 여보" },
  { kanji: "ボタン", hiragana: "", meaning: "버튼, 단추" },
  { kanji: "遊ぶ", hiragana: "あそぶ", meaning: "놀다" },
  { kanji: "英語", hiragana: "えいご", meaning: "영어" },
];
