// lib/words_11_15.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_11_15: Word[] = [
  { kanji: "四", hiragana: "し, よん", meaning: "4" },
  { kanji: "夕飯", hiragana: "ゆうはん", meaning: "저녁밥" },
  { kanji: "同じ", hiragana: "おなじ", meaning: "같음, 통일" },
  { kanji: "小さな", hiragana: "ちいさな", meaning: "작은" },
  { kanji: "ズボン", hiragana: "", meaning: "바지" },
  { kanji: "お腹", hiragana: "おなか", meaning: "배" },
  { kanji: "生徒", hiragana: "せいと", meaning: "학생, 생도" },
  { kanji: "答える", hiragana: "こたえる", meaning: "대답하다" },
  { kanji: "クラス", hiragana: "", meaning: "클래스, 학급, 등급, 계급" },
  { kanji: "夜", hiragana: "よる", meaning: "밤" },
  { kanji: "電気", hiragana: "でんき", meaning: "전기" },
  { kanji: "塩", hiragana: "しお", meaning: "소금" },
  { kanji: "丸い", hiragana: "まるい", meaning: "둥글다" },
  { kanji: "ハンカチ", hiragana: "", meaning: "손수건" },
  { kanji: "遅い", hiragana: "おそい", meaning: "늦다, 느리다, 더디다" },
  { kanji: "四月", hiragana: "しがつ", meaning: "4월" },
  { kanji: "質問", hiragana: "しつもん", meaning: "질문" },
  { kanji: "回る", hiragana: "まわる", meaning: "돌다, 회전하다" },
  { kanji: "桜", hiragana: "さくら", meaning: "벚꽃" },
  { kanji: "全体", hiragana: "ぜんたい", meaning: "전체" },
  { kanji: "咲く", hiragana: "さく", meaning: "피다, 꽃이 피다" },
  { kanji: "広がる", hiragana: "ひろがる", meaning: "퍼지다, 번지다, 넓어지다" },
  { kanji: "穿く", hiragana: "はく", meaning: "입다, 바지를 입다" },
  { kanji: "猫", hiragana: "ねこ", meaning: "고양이" },
  { kanji: "過ち", hiragana: "あやまち", meaning: "잘못, 실수, 저지른 죄" },
  { kanji: "物", hiragana: "もの", meaning: "것, 물건, 물체" },
  { kanji: "繰り返す", hiragana: "くりかえす", meaning: "되풀이하다, 반복하다" },
  { kanji: "見える", hiragana: "みえる", meaning: "보이다, 눈에 들어오다" },
  { kanji: "目元", hiragana: "めもと", meaning: "눈매, 눈언저리" },
  { kanji: "砂糖", hiragana: "さとう", meaning: "설탕" },
  { kanji: "ほくろ", hiragana: "", meaning: "점, 흑자" },
  { kanji: "半々", hiragana: "はんはん", meaning: "반반, 반반씩" },
  { kanji: "壊す", hiragana: "こわす", meaning: "파괴하다, 고장내다, 탈을 내다, 망치다" },
  { kanji: "入れる", hiragana: "いれる", meaning: "넣다, 속에 집어넣다, 들어가게 하다" },
  { kanji: "組", hiragana: "くみ", meaning: "조, 반, 쌍, 짝" },
  { kanji: "円やか", hiragana: "まろやか", meaning: "둥근 모양, 둥그스름한 모양" },
  { kanji: "分ける", hiragana: "わける", meaning: "나누다, 가르다, 구분하다" },
  { kanji: "可愛い", hiragana: "かわいい", meaning: "귀엽다, 사랑스럽다, 작다" },
  { kanji: "少女", hiragana: "しょうじょ", meaning: "소녀" },
  { kanji: "汗", hiragana: "あせ", meaning: "땀" },
  { kanji: "拭く", hiragana: "ふく", meaning: "닦다" },
  { kanji: "頭", hiragana: "あたま", meaning: "머리" },
  { kanji: "いつも", hiragana: "", meaning: "언제나, 늘, 항상" },
  { kanji: "青い", hiragana: "あおい", meaning: "파랗다, 푸르다" },
  { kanji: "一人", hiragana: "ひとり", meaning: "한 사람, 한 명, 혼자" },
  { kanji: "眼鏡", hiragana: "めがね", meaning: "안경" },
  { kanji: "帰る", hiragana: "かえる", meaning: "돌아가다, 돌아오다" },
  { kanji: "南", hiragana: "みなみ", meaning: "남, 남쪽" },
  { kanji: "一昨年", hiragana: "おととし", meaning: "재작년" },
  { kanji: "寝る", hiragana: "ねる", meaning: "자다, 잠을 자다" },
  { kanji: "こんにちは", hiragana: "こんにちは", meaning: "안녕하세요, 낮 인사" },
  { kanji: "おじいさん", hiragana: "", meaning: "할아버지, 영감님" },
  { kanji: "喫茶店", hiragana: "きっさてん", meaning: "찻집, 다방" },
  { kanji: "話", hiragana: "はなし", meaning: "이야기, 말" },
  { kanji: "大人", hiragana: "おとな", meaning: "어른" },
  { kanji: "奥さん", hiragana: "おくさん", meaning: "부인" },
  { kanji: "千", hiragana: "せん", meaning: "천, 1000" },
  { kanji: "暗い", hiragana: "くらい", meaning: "어둡다, 캄캄하다" },
  { kanji: "やめる", hiragana: "やめる", meaning: "그만두다, 중지하다, 끊다" },
  { kanji: "虹が出る", hiragana: "にじがでる", meaning: "무지개가 뜨다" },
  { kanji: "差別", hiragana: "さべつ", meaning: "차별" },
  { kanji: "とうとう", hiragana: "", meaning: "결국, 드디어, 마침내" },
  { kanji: "去年", hiragana: "きょねん", meaning: "작년" },
  { kanji: "離婚", hiragana: "りこん", meaning: "이혼" },
  { kanji: "全般的", hiragana: "ぜんぱんてき", meaning: "전반적" },
  { kanji: "位", hiragana: "くらい", meaning: "숫자의 자릿수, 품격, 지위, 자리" },
  { kanji: "天気", hiragana: "てんき", meaning: "날씨" },
  { kanji: "打つ", hiragana: "うつ", meaning: "치다" },
  { kanji: "おやすみなさい", hiragana: "", meaning: "편히 쉬세요, 안녕히 주무세요" },
  { kanji: "注文", hiragana: "ちゅうもん", meaning: "주문" },
  { kanji: "決まる", hiragana: "きまる", meaning: "정해지다, 결정되다" },
  { kanji: "大人しい", hiragana: "おとなしい", meaning: "온순하다, 얌전하다" },
  { kanji: "待ち合わせる", hiragana: "まちあわせる", meaning: "만나기로 하다" },
  { kanji: "ゼロ", hiragana: "", meaning: "0, 제로" },
  { kanji: "多い", hiragana: "おおい", meaning: "많다" },
  { kanji: "コーヒー", hiragana: "", meaning: "커피" },
  { kanji: "家", hiragana: "いえ", meaning: "집" },
  { kanji: "雨", hiragana: "あめ", meaning: "비" },
  { kanji: "大きい", hiragana: "おおきい", meaning: "크다" },
  { kanji: "こちら", hiragana: "", meaning: "이쪽, 여기, 이곳" },
  { kanji: "十日", hiragana: "とおか", meaning: "열흘, 10일" },
  { kanji: "服", hiragana: "ふく", meaning: "옷" },
  { kanji: "夏", hiragana: "なつ", meaning: "여름" },
  { kanji: "春", hiragana: "はる", meaning: "봄" },
  { kanji: "今朝", hiragana: "けさ", meaning: "오늘 아침" },
  { kanji: "時々", hiragana: "ときどき", meaning: "때때로, 가끔" },
  { kanji: "出る", hiragana: "でる", meaning: "나가다, 나오다" },
  { kanji: "側", hiragana: "そば, がわ", meaning: "옆, 측, 곁, 쪽" },
  { kanji: "勝つ", hiragana: "かつ", meaning: "이기다, 승리하다" },
  { kanji: "開かれる", hiragana: "ひらかれる", meaning: "열리다, 개최되다" },
  { kanji: "界隈", hiragana: "かいわい", meaning: "근처, 부근, 일대" },
  { kanji: "作る", hiragana: "つくる", meaning: "만들다, 만들어내다" },
  { kanji: "飲食店", hiragana: "いんしょくてん", meaning: "음식점" },
  { kanji: "変える", hiragana: "かえる", meaning: "바꾸다, 변하다, 고치다" },
  { kanji: "各社", hiragana: "かくしゃ", meaning: "각 사, 각각의 회사" },
  { kanji: "別荘", hiragana: "べっそう", meaning: "별장" },
  { kanji: "特徴", hiragana: "とくちょう", meaning: "특징" },
  { kanji: "過ごす", hiragana: "すごす", meaning: "보내다, 지내다, 경과시키다, 시간을 보내다" },
  { kanji: "比較", hiragana: "ひかく", meaning: "비교" },
  { kanji: "早起き", hiragana: "はやおき", meaning: "일찍 일어남" },
  { kanji: "建てる", hiragana: "たてる", meaning: "세우다, 짓다" },
  { kanji: "皮膚", hiragana: "ひふ", meaning: "피부" },
  { kanji: "試合", hiragana: "しあい", meaning: "시합" },
  { kanji: "痛み", hiragana: "痛み", meaning: "아픔, 통증" },
  { kanji: "結構", hiragana: "けっこう", meaning: "꽤, 그런대로, 충분함, 이제 됐음" },
  { kanji: "事件", hiragana: "じけん", meaning: "사건" },
  { kanji: "感じる", hiragana: "かんじる", meaning: "느끼다" },
  { kanji: "審問", hiragana: "しんもん", meaning: "심문, 일일이 따져 물음" },
  { kanji: "遊ぶ", hiragana: "あそぶ", meaning: "놀다" },
  { kanji: "降りる", hiragana: "おりる", meaning: "내리다" },
  { kanji: "そんな", hiragana: "", meaning: "그런, 그러한, 그렇게" },
  { kanji: "カップ", hiragana: "", meaning: "컵" },
  { kanji: "口", hiragana: "くち", meaning: "입" },
  { kanji: "女の子", hiragana: "おんなのこ", meaning: "여자아이" },
  { kanji: "紙", hiragana: "かみ", meaning: "종이" },
  { kanji: "毎年", hiragana: "まいとし, まいねん", meaning: "매년" },
  { kanji: "女", hiragana: "おんな", meaning: "여자" },
  { kanji: "黒い", hiragana: "くろい", meaning: "검다, 까맣다" },
  { kanji: "ご飯", hiragana: "ごはん", meaning: "밥, 식사" },
  { kanji: "傘", hiragana: "かさ", meaning: "우산" },
  { kanji: "花瓶", hiragana: "かびん", meaning: "꽃병" },
  { kanji: "誰", hiragana: "だれ", meaning: "누구" },
  { kanji: "お母さん", hiragana: "おかあさん", meaning: "어머니" },
  { kanji: "タクシー", hiragana: "", meaning: "택시" },
  { kanji: "停留所", hiragana: "ていりゅうじょ", meaning: "정류장" },
  { kanji: "男", hiragana: "おとこ", meaning: "남자" },
  { kanji: "必要", hiragana: "ひつよう", meaning: "필요" },
  { kanji: "茶碗", hiragana: "ちゃわん", meaning: "밥공기" },
  { kanji: "使う", hiragana: "つかう", meaning: "쓰다, 사용하다" },
  { kanji: "山盛り", hiragana: "やまもり", meaning: "고봉으로 담다, 산처럼 수북이" },
  { kanji: "軽い", hiragana: "かるい", meaning: "가볍다" },
  { kanji: "盛る", hiragana: "もる", meaning: "그릇에 많이 담다, 높이 쌓아 올리다" },
  { kanji: "告白", hiragana: "こくはく", meaning: "고백" },
  { kanji: "貸す", hiragana: "かす", meaning: "빌려주다, 이용하게 하다" },
  { kanji: "仮に", hiragana: "かりに", meaning: "만일, 만약, 임시로" },
  { kanji: "もらう", hiragana: "", meaning: "받다" },
  { kanji: "書く", hiragana: "かく", meaning: "쓰다" },
  { kanji: "生ける", hiragana: "いける", meaning: "꽂다, 흙에 심다, 꽃꽂이하다" },
  { kanji: "今ごろ", hiragana: "いまごろ", meaning: "지금쯤, 이맘때" },
  { kanji: "優しい", hiragana: "やさしい", meaning: "상냥하다, 다정하다" },
  { kanji: "梅雨", hiragana: "つゆ", meaning: "장마, 장마철" },
  { kanji: "乗る", hiragana: "のる", meaning: "타다, 탈것에 타다" },
  { kanji: "気がある", hiragana: "きがある", meaning: "마음이 있다, 관심이 있다" },
  { kanji: "若い", hiragana: "わかい", meaning: "젊다, 어리다" },
  { kanji: "テーブル", hiragana: "", meaning: "테이블" },
  { kanji: "右", hiragana: "みぎ", meaning: "오른쪽, 우측, 우" },
  { kanji: "靴", hiragana: "くつ", meaning: "신발, 구두" },
  { kanji: "コップ", hiragana: "", meaning: "컵" },
  { kanji: "便利", hiragana: "べんり", meaning: "편리" },
  { kanji: "出口", hiragana: "でぐち", meaning: "출구" },
  { kanji: "早い", hiragana: "はやい", meaning: "빠르다, 이르다" },
  { kanji: "撮る", hiragana: "とる", meaning: "찍다, 사진을 찍다" },
  { kanji: "犬", hiragana: "いぬ", meaning: "개" },
  { kanji: "ここ", hiragana: "", meaning: "여기, 이곳" },
  { kanji: "一", hiragana: "いち", meaning: "1, 일, 하나" },
  { kanji: "あなた", hiragana: "", meaning: "당신, 여보" },
  { kanji: "ボタン", hiragana: "", meaning: "버튼, 단추" },
  { kanji: "英語", hiragana: "えいご", meaning: "영어" },
  { kanji: "向き合う", hiragana: "むきあう", meaning: "마주 보다, 마주 대하다" },
  { kanji: "連れ戻す", hiragana: "つれもどす", meaning: "데려오다, 다시 원래 장소로 데려오다" },
  { kanji: "市庁", hiragana: "しちょう", meaning: "시청" },
  { kanji: "一休み", hiragana: "ひとやすみ", meaning: "잠깐 쉼" },
  { kanji: "脱ぐ", hiragana: "ぬぐ", meaning: "벗다" },
  { kanji: "学生", hiragana: "がくせい", meaning: "학생" },
  { kanji: "注ぐ", hiragana: "そそぐ", meaning: "쏟다, 따르다, 붓다" },
  { kanji: "呼び鈴", hiragana: "よびりん", meaning: "초인종" },
  { kanji: "非常に", hiragana: "ひじょうに", meaning: "매우, 상당히" },
  { kanji: "押す", hiragana: "おす", meaning: "밀다, 누르다" },
  { kanji: "探す", hiragana: "さがす", meaning: "찾다" },
  { kanji: "水鉄砲", hiragana: "みずでっぽう", meaning: "물총" },
  { kanji: "写真", hiragana: "しゃしん", meaning: "사진" },
  { kanji: "世界中", hiragana: "せかいじゅう", meaning: "전 세계, 온 세계" },
  { kanji: "逃げる", hiragana: "にげる", meaning: "도망치다, 달아나다" },
  { kanji: "通用", hiragana: "つうよう", meaning: "통용, 널리쓰임" },
  { kanji: "戻る", hiragana: "もどる", meaning: "되돌아가다, 되돌아오다" },
  { kanji: "連れる", hiragana: "つれる", meaning: "동행하다, 동반하다, 데리고 가다, 데리고 오다" },
];
