// lib/words_01_05.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_01_05: Word[] = [
  { kanji: "うるさい", hiragana: "", meaning: "시끄럽다, 귀찮다" },
  { kanji: "手", hiragana: "て", meaning: "손" },
  { kanji: "座る", hiragana: "すわる", meaning: "앉다" },
  { kanji: "悪い", hiragana: "わるい", meaning: "나쁘다" },
  { kanji: "紅茶", hiragana: "こうちゃ", meaning: "홍차" },
  { kanji: "上げる", hiragana: "あげる", meaning: "올리다, 얹다" },
  { kanji: "切手", hiragana: "きって", meaning: "수표, 어음, 우표" },
  { kanji: "買い物", hiragana: "かいもの", meaning: "물건을 삼, 쇼핑" },
  { kanji: "晩ご飯", hiragana: "ばんごはん", meaning: "저녁밥, 저녁식사" },
  { kanji: "飛ぶ", hiragana: "とぶ", meaning: "날다" },
  { kanji: "起きる", hiragana: "おきる", meaning: "일어나다, 기상하다" },
  { kanji: "ある", hiragana: "", meaning: "있다, (무생물) 있다" },
  { kanji: "灰皿", hiragana: "はいざら", meaning: "재떨이" },
  { kanji: "家族", hiragana: "かぞく", meaning: "가족" },
  { kanji: "お姉さん", hiragana: "おねえさん", meaning: "언니, 누나" },
  { kanji: "九日", hiragana: "ここのか", meaning: "9일, 아흐레" },
  { kanji: "言う", hiragana: "いう", meaning: "말하다" },
  { kanji: "セーター", hiragana: "", meaning: "스웨터" },
  { kanji: "聞く", hiragana: "きく", meaning: "듣다, 묻다" },
  { kanji: "お父さん", hiragana: "おとうさん", meaning: "아버지" },
  { kanji: "コビー", hiragana: "", meaning: "복사" },
  { kanji: "風", hiragana: "かぜ", meaning: "바람" },
  { kanji: "庭", hiragana: "にわ", meaning: "정원, 뜰, 마당" },
  { kanji: "二つ", hiragana: "ふたつ", meaning: "두 개, 둘" },
  { kanji: "母", hiragana: "はは", meaning: "어머니" },
  { kanji: "入る", hiragana: "はいる", meaning: "들어오다, 들어가다" },
  { kanji: "泳ぐ", hiragana: "およぐ", meaning: "헤엄치다, 수영을 하다" },
  { kanji: "始まる", hiragana: "はじまる", meaning: "시작하다, 개시되다" },
  { kanji: "花", hiragana: "はな", meaning: "꽃" },
  { kanji: "鳥", hiragana: "とり", meaning: "새" },
  { kanji: "池", hiragana: "いけ", meaning: "연못" },
  { kanji: "ポケット", hiragana: "", meaning: "포켓, 주머니" },
  { kanji: "アパート", hiragana: "", meaning: "아파트" },
  { kanji: "病院", hiragana: "びょういん", meaning: "병원" },
  { kanji: "バス", hiragana: "", meaning: "버스" },
  { kanji: "店", hiragana: "みせ", meaning: "가게, 상점, 점포" },
  { kanji: "牛肉", hiragana: "ぎゅうにく", meaning: "소고기" },
  { kanji: "危ない", hiragana: "あぶない", meaning: "위험하다" },
  { kanji: "待つ", hiragana: "まつ", meaning: "기다리다" },
  { kanji: "楽しい", hiragana: "たのしい", meaning: "즐겁다" },
  { kanji: "意味", hiragana: "いみ", meaning: "의미" },
  { kanji: "大変", hiragana: "たいへん", meaning: "몹시, 매우, 대사건, 큰일, 힘듦" },
  { kanji: "置く", hiragana: "おく", meaning: "두다, 놓다" },
  { kanji: "妹", hiragana: "いもうと", meaning: "여동생" },
  { kanji: "明るい", hiragana: "あかるい", meaning: "밝다, 환하다, 명랑하다" },
  { kanji: "大きな", hiragana: "おおきな", meaning: "큰" },
  { kanji: "二十歳", hiragana: "はたち", meaning: "스무 살" },
  { kanji: "いくつ", hiragana: "", meaning: "몇 살, 몇 개" },
  { kanji: "小さい", hiragana: "ちいさい", meaning: "작다" },
  { kanji: "嫌い", hiragana: "きらい", meaning: "싫음, 마음에 들지 않음" },
  { kanji: "背", hiragana: "せ", meaning: "등, 키" },
  { kanji: "寒い", hiragana: "さむい", meaning: "춥다" },
  { kanji: "一昨日", hiragana: "おととい", meaning: "그저께" },
  { kanji: "レストラン", hiragana: "", meaning: "레스토랑" },
  { kanji: "二人", hiragana: "ふたり", meaning: "두 사람, 두 명" },
  { kanji: "薄い", hiragana: "うすい", meaning: "얇다, 싱겁다, 적다" },
  { kanji: "歌", hiragana: "うた", meaning: "노래" },
  { kanji: "椅子", hiragana: "いす", meaning: "의자" },
  { kanji: "大勢", hiragana: "おおぜい", meaning: "많은 사람, 여럿" },
  { kanji: "締める", hiragana: "しめる", meaning: "죄다, 조르다, 매다" },
  { kanji: "今日", hiragana: "きょう", meaning: "오늘" },
  { kanji: "薬", hiragana: "くすり", meaning: "약" },
  { kanji: "次", hiragana: "つぎ", meaning: "다음" },
  { kanji: "牛乳", hiragana: "ぎゅうにゅう", meaning: "우유" },
  { kanji: "パン", hiragana: "", meaning: "빵" },
  { kanji: "西", hiragana: "にし", meaning: "서쪽, 서" },
  { kanji: "魚", hiragana: "さかな", meaning: "물고기, 생선" },
  { kanji: "来る", hiragana: "くる", meaning: "오다" },
  { kanji: "開く", hiragana: "あく", meaning: "열리다, 시작하다, 영업하다" },
  { kanji: "そこ", hiragana: "", meaning: "거기, 그곳" },
  { kanji: "おばさん", hiragana: "", meaning: "아주머니, 숙모, 고모, 이모" },
  { kanji: "六日", hiragana: "むいか", meaning: "6일, 엿새" },
  { kanji: "足", hiragana: "あし", meaning: "발, 다리" },
  { kanji: "絵", hiragana: "え", meaning: "그림" },
];
