// lib/words_16_20.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_16_20: Word[] = [
  { kanji: "テレビ", hiragana: "", meaning: "텔레비전, 티비" },
  { kanji: "初めまして", hiragana: "はじめまして", meaning: "처음 뵙겠습니다" },
  { kanji: "ドア", hiragana: "", meaning: "문, 도어" },
  { kanji: "作文", hiragana: "さくぶん", meaning: "작문" },
  { kanji: "六", hiragana: "ろく", meaning: "6" },
  { kanji: "卵", hiragana: "たまご", meaning: "알, 달걀, 계란" },
  { kanji: "飲み物", hiragana: "のみもの", meaning: "마실 것, 음료" },
  { kanji: "あの", hiragana: "", meaning: "저, 그" },
  { kanji: "節倹", hiragana: "せっけん", meaning: "절약, 절검" },
  { kanji: "ゆっくり", hiragana: "", meaning: "천천히, 서서히" },
  { kanji: "下", hiragana: "した", meaning: "아래" },
  { kanji: "散歩", hiragana: "さんぽ", meaning: "산책, 산보" },
  { kanji: "仕事", hiragana: "しごと", meaning: "일, 직업, 업무" },
  { kanji: "どちら", hiragana: "", meaning: "어느쪽" },
  { kanji: "作る", hiragana: "つくる", meaning: "만들다" },
  { kanji: "売れる", hiragana: "うれる", meaning: "팔리다, 널리 알려지다" },
  { kanji: "朝", hiragana: "あさ", meaning: "아침" },
  { kanji: "回転", hiragana: "かいてん", meaning: "회전" },
  { kanji: "日課", hiragana: "にっか", meaning: "일과" },
  { kanji: "間違い", hiragana: "まちがい", meaning: "틀림, 실수" },
  { kanji: "向く", hiragana: "むく", meaning: "향하다, 얼굴을 돌리다" },
  { kanji: "対", hiragana: "たい", meaning: "대, 몇대몇의 대" },
  { kanji: "社会", hiragana: "しゃかい", meaning: "사회" },
  { kanji: "産む", hiragana: "うむ", meaning: "낳다, 출산하다" },
  { kanji: "保障", hiragana: "ほしょう", meaning: "보장" },
  { kanji: "旨", hiragana: "むね", meaning: "으뜸, 가장 으뜸으로 치다" },
  { kanji: "制度", hiragana: "せいど", meaning: "제도" },
  { kanji: "第一", hiragana: "だいいち", meaning: "제일, 첫 번째, 가장 중요한 것" },
  { kanji: "安全", hiragana: "あんぜん", meaning: "안전" },
  { kanji: "運転", hiragana: "うんてん", meaning: "운전" },
  { kanji: "兄", hiragana: "あに", meaning: "형" },
  { kanji: "三つ", hiragana: "みっつ", meaning: "셋" },
  { kanji: "強い", hiragana: "つよい", meaning: "강하다, 세다" },
  { kanji: "嫌", hiragana: "いや", meaning: "싫음" },
  { kanji: "毎月", hiragana: "まいつき", meaning: "매월, 매달" },
  { kanji: "五", hiragana: "ご", meaning: "5" },
  { kanji: "どう", hiragana: "", meaning: "어때, 어떻게" },
  { kanji: "今月", hiragana: "こんげつ", meaning: "이달, 이번 달" },
  { kanji: "ホテル", hiragana: "", meaning: "호텔" },
  { kanji: "目", hiragana: "め", meaning: "눈" },
  { kanji: "海", hiragana: "うみ", meaning: "바다" },
  { kanji: "蕎麦", hiragana: "そば", meaning: "소바, 메밀 국수" },
  { kanji: "日曜日", hiragana: "にちようび", meaning: "일요일" },
  { kanji: "いつ", hiragana: "", meaning: "언제, 어느때" },
  { kanji: "カメラ", hiragana: "", meaning: "카메라" },
  { kanji: "少ない", hiragana: "すくない", meaning: "적다, 드물다" },
  { kanji: "料理", hiragana: "りょうり", meaning: "요리" },
  { kanji: "喧嘩", hiragana: "けんか", meaning: "다툼, 싸움, 소란" },
  { kanji: "美味しい", hiragana: "おいしい", meaning: "맛있다" },
  { kanji: "理屈", hiragana: "りくつ", meaning: "도리, 이론, 이치" },
  { kanji: "支払う", hiragana: "しはらう", meaning: "지불하다, 지급하다" },
  { kanji: "赤字", hiragana: "あかじ", meaning: "적자, 결손, 빨간색 글자" },
  { kanji: "泊まる", hiragana: "とまる", meaning: "묵다, 숙박하다" },
  { kanji: "沈む", hiragana: "しずむ", meaning: "가라앉다" },
  { kanji: "学校", hiragana: "がっこう", meaning: "학교" },
  { kanji: "新品", hiragana: "しんぴん", meaning: "신품" },
  { kanji: "同様", hiragana: "どうよう", meaning: "마찬가지, 같은 모양" },
  { kanji: "彼女", hiragana: "かのじょ", meaning: "그녀" },
  { kanji: "様な", hiragana: "ような", meaning: "같은, ~와 같은" },
  { kanji: "名前", hiragana: "なまえ", meaning: "이름" },
  { kanji: "賑やか", hiragana: "にぎやか", meaning: "활기참, 번화함" },
  { kanji: "要る", hiragana: "いる", meaning: "필요하다" },
  { kanji: "教室", hiragana: "きょうしつ", meaning: "교실" },
  { kanji: "シャツ", hiragana: "", meaning: "셔츠" },
  { kanji: "カレンダー", hiragana: "", meaning: "달력, 캘린더" },
  { kanji: "テープ", hiragana: "", meaning: "테이프" },
  { kanji: "毎朝", hiragana: "まいあさ", meaning: "매일 아침" },
  { kanji: "する", hiragana: "", meaning: "하다" },
  { kanji: "高い", hiragana: "たかい", meaning: "비싸다, 높다" },
  { kanji: "道", hiragana: "みち", meaning: "길, 도로" },
  { kanji: "勉強", hiragana: "べんきょう", meaning: "공부" },
  { kanji: "だけ", hiragana: "", meaning: "~밖에, ~만큼, ~뿐, ~만" },
  { kanji: "鼻", hiragana: "はな", meaning: "코, 후각" },
  { kanji: "昼", hiragana: "ひる", meaning: "낮, 점심" },
  { kanji: "忘れる", hiragana: "わすれる", meaning: "잊다, 기억이 없어지다" },
  { kanji: "余波", hiragana: "よは", meaning: "여파, 영향" },
  { kanji: "掃除", hiragana: "そうじ", meaning: "청소" },
  { kanji: "波", hiragana: "なみ", meaning: "파도" },
  { kanji: "厚い", hiragana: "あつい", meaning: "두껍다" },
  { kanji: "努力", hiragana: "どりょく", meaning: "노력" },
  { kanji: "何枚", hiragana: "なんまい", meaning: "몇 장" },
  { kanji: "働く", hiragana: "はたらく", meaning: "일하다, 노동하다" },
  { kanji: "着込む", hiragana: "きこむ", meaning: "껴입다" },
  { kanji: "種類", hiragana: "しゅるい", meaning: "종류" },
  { kanji: "購入", hiragana: "こうにゅう", meaning: "구입" },
  { kanji: "漏水", hiragana: "ろうすい", meaning: "누수, 물이 샘" },
  { kanji: "箇所", hiragana: "かしょ", meaning: "개소, 장소, 곳, 부분" },
  { kanji: "押さえる", hiragana: "おさえる", meaning: "누르다, 억누르다" },
  { kanji: "円", hiragana: "えん", meaning: "원, 엔, 둥긂, 둥근 것" },
  { kanji: "外", hiragana: "そと", meaning: "밖, 바깥" },
  { kanji: "物", hiragana: "もの", meaning: "것, 물건" },
  { kanji: "近く", hiragana: "ちかく", meaning: "가까운 곳, 근처" },
  { kanji: "休む", hiragana: "やすむ", meaning: "쉬다" },
  { kanji: "曲がる", hiragana: "まがる", meaning: "구부러지다, 굽다, 방향을 바꾸다, 돌다" },
  { kanji: "不味い", hiragana: "まずい", meaning: "맛이 없다" },
  { kanji: "七日", hiragana: "なのか", meaning: "7일, 이레" },
  { kanji: "冬", hiragana: "ふゆ", meaning: "겨울" },
  { kanji: "兄弟", hiragana: "きょうだい", meaning: "형제" },
  { kanji: "あちら", hiragana: "", meaning: "저쪽, 저기" },
  { kanji: "困る", hiragana: "こまる", meaning: "곤란하다" },
  { kanji: "ストーブ", hiragana: "", meaning: "난로, 스토브" },
  { kanji: "横", hiragana: "よこ", meaning: "옆, 가로" },
  { kanji: "新しい", hiragana: "あたらしい", meaning: "새롭다" },
  { kanji: "ノート", hiragana: "", meaning: "노트" },
  { kanji: "大切", hiragana: "たいせつ", meaning: "중요함, 귀중함, 소중함" },
  { kanji: "学費", hiragana: "がくひ", meaning: "학비" },
  { kanji: "移す", hiragana: "うつす", meaning: "옮기다, 자리를 바꾸다, 이동시키다" },
  { kanji: "燃やす", hiragana: "もやす", meaning: "불태우다, 불을 붙여서 타게 하다" },
  { kanji: "黙る", hiragana: "だまる", meaning: "말을 하지 않다, 가만히 있다" },
  { kanji: "年を取る", hiragana: "としをとる", meaning: "나이를 먹다, 늙다" },
  { kanji: "割り込む", hiragana: "わりこむ", meaning: "비집고 들어가다, 끼어들다, 새치기하다" },
  { kanji: "腰", hiragana: "こし", meaning: "허리" },
  { kanji: "毎日", hiragana: "まいにち", meaning: "매일" },
  { kanji: "苦労", hiragana: "くろう", meaning: "고생, 애씀" },
  { kanji: "実る", hiragana: "みのる", meaning: "결실하다, 열매를 맺다, 노력의 보람이 나타나다" },
  { kanji: "乾く", hiragana: "かわく", meaning: "마르다, 건조하다" },
  { kanji: "冷たい", hiragana: "つめたい", meaning: "차갑다, 차다, 냉정하다" },
  { kanji: "別別", hiragana: "べつべつ", meaning: "따로따로임, 각각임, 제각기임" },
  { kanji: "進む", hiragana: "すすむ", meaning: "나아가다" },
  { kanji: "夏休み", hiragana: "なつやすみ", meaning: "여름방학, 여름휴가" },
  { kanji: "食べ物", hiragana: "たべもの", meaning: "먹을 것, 음식" },
  { kanji: "どういたしまして", hiragana: "", meaning: "천만에요, 별 말씀을요" },
  { kanji: "階段", hiragana: "かいだん", meaning: "계단" },
  { kanji: "結婚", hiragana: "けっこん", meaning: "결혼" },
  { kanji: "葉書", hiragana: "はがき", meaning: "엽서" },
  { kanji: "食堂", hiragana: "しょくどう", meaning: "식당" },
  { kanji: "長い", hiragana: "ながい", meaning: "길다" },
  { kanji: "スカート", hiragana: "", meaning: "스커트, 치마" },
  { kanji: "ボールペン", hiragana: "", meaning: "볼펜" },
  { kanji: "弱い", hiragana: "よわい", meaning: "약하다" },
  { kanji: "去年", hiragana: "きょねん", meaning: "지난해, 작년" },
  { kanji: "被る", hiragana: "かぶる", meaning: "쓰다, 뒤집어쓰다, 겹치다" },
  { kanji: "私", hiragana: "わたし", meaning: "나, 저" },
  { kanji: "出す", hiragana: "だす", meaning: "내다, 내놓다, 꺼내다" },
  { kanji: "熱い", hiragana: "あつい", meaning: "뜨겁다, 열도가 높다" },
  { kanji: "運動", hiragana: "うんどう", meaning: "운동" },
  { kanji: "好き", hiragana: "すき", meaning: "좋아함" },
  { kanji: "不足", hiragana: "ぶそく", meaning: "부족" },
  { kanji: "失礼", hiragana: "しつれい", meaning: "실례, 미안" },
  { kanji: "体力", hiragana: "たいりょく", meaning: "체력" },
  { kanji: "足下", hiragana: "あしもと", meaning: "발 밑" },
  { kanji: "最初", hiragana: "さいしょ", meaning: "처음, 최초, 맨 처음" },
  { kanji: "気を付ける", hiragana: "きをつける", meaning: "조심하다, 주의하다, 정신차리다" },
  { kanji: "痛める", hiragana: "いためる", meaning: "아프게 하다, 고통을 주다" },
  { kanji: "出会い", hiragana: "であい", meaning: "처음으로 만남" },
  { kanji: "郵便局", hiragana: "ゆうびんきょく", meaning: "우체국" },
  { kanji: "罪", hiragana: "つみ", meaning: "죄, 못할짓" },
  { kanji: "販売", hiragana: "はんばい", meaning: "판매" },
  { kanji: "信じる", hiragana: "しんじる", meaning: "믿다, 확신하다, 신뢰하다" },
  { kanji: "社員", hiragana: "しゃいん", meaning: "사원, 회사원" },
  { kanji: "昼食", hiragana: "ちゅうしょく", meaning: "점심, 주식" },
  { kanji: "流行る", hiragana: "はやる", meaning: "유행하다, 인기가 있다" },
];