// lib/words_16_20.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_16_20: Word[] = [
  { kanji: "テレビ", hiragana: "", meaning: "텔레비전" },
  { kanji: "ドア", hiragana: "", meaning: "문, 도어" },
  { kanji: "初めまして", hiragana: "はじめまして", meaning: "처음 뵙겠습니다" },
  { kanji: "作文", hiragana: "さくぶん", meaning: "작문" },
  { kanji: "六", hiragana: "ろく", meaning: "6" },
  { kanji: "卵", hiragana: "たまご", meaning: "알, 달걀, 계란" },
  { kanji: "飲み物", hiragana: "のみもの", meaning: "마실 것, 음료" },
  { kanji: "あの", hiragana: "", meaning: "저, 그" },
  { kanji: "節倹", hiragana: "せっけん", meaning: "절약, 절검" },
  { kanji: "ゆっくり", hiragana: "", meaning: "천천히, 서서히" },
  { kanji: "下", hiragana: "した", meaning: "아래" },
  { kanji: "散歩", hiragana: "さんぽ", meaning: "산책, 산보" },
  { kanji: "仕事", hiragana: "しごと", meaning: "일, 직업, 업무" },
  { kanji: "どちら", hiragana: "", meaning: "어느 쪽" },
  { kanji: "作る", hiragana: "つくる", meaning: "만들다" },
  { kanji: "強い", hiragana: "つよい", meaning: "강하다, 세다" },
  { kanji: "嫌", hiragana: "いや", meaning: "싫음" },
  { kanji: "毎月", hiragana: "まいつき", meaning: "매월, 매달" },
  { kanji: "五", hiragana: "ご", meaning: "5" },
  { kanji: "どう", hiragana: "", meaning: "어때, 어떻게" },
  { kanji: "今月", hiragana: "こんげつ", meaning: "이달, 이번달" },
  { kanji: "ホテル", hiragana: "", meaning: "호텔" },
  { kanji: "目", hiragana: "め", meaning: "눈" },
  { kanji: "海", hiragana: "うみ", meaning: "바다" },
  { kanji: "蕎麦", hiragana: "そば", meaning: "메밀 국수" },
  { kanji: "日曜日", hiragana: "にちようび", meaning: "일요일" },
  { kanji: "いつ", hiragana: "", meaning: "언제, 어느 때" },
  { kanji: "カメラ", hiragana: "", meaning: "카메라" },
  { kanji: "少ない", hiragana: "すくない", meaning: "적다, 드물다" },
  { kanji: "料理", hiragana: "りょうり", meaning: "요리" },
  { kanji: "名前", hiragana: "なまえ", meaning: "이름" },
  { kanji: "賑やか", hiragana: "にぎやか", meaning: "활기참, 번화함" },
  { kanji: "要る", hiragana: "いる", meaning: "필요하다" },
  { kanji: "教室", hiragana: "きょうしつ", meaning: "교실" },
  { kanji: "シャツ", hiragana: "", meaning: "셔츠" },
  { kanji: "カレンダー", hiragana: "", meaning: "달력, 캘린더" },
  { kanji: "テープ", hiragana: "", meaning: "테이프" },
  { kanji: "毎朝", hiragana: "まいあさ", meaning: "매일 아침" },
  { kanji: "する", hiragana: "", meaning: "하다" },
  { kanji: "高い", hiragana: "たかい", meaning: "비싸다, 높다" },
  { kanji: "道", hiragana: "みち", meaning: "길, 도로" },
  { kanji: "勉強", hiragana: "べんきょう", meaning: "공부" },
  { kanji: "だけ", hiragana: "", meaning: "~밖에, ~만큼, ~뿐, ~만" },
  { kanji: "鼻", hiragana: "はな", meaning: "코, 후각" },
  { kanji: "昼", hiragana: "ひる", meaning: "낮" },
  { kanji: "外", hiragana: "そと", meaning: "밖, 바깥" },
  { kanji: "物", hiragana: "もの", meaning: "것, 물건" },
  { kanji: "近く", hiragana: "ちかく", meaning: "가까운 곳, 근처" },
  { kanji: "休む", hiragana: "やすむ", meaning: "쉬다" },
  { kanji: "曲がる", hiragana: "まがる", meaning: "구부러지다, 굽다, 방향을 바꾸다, 돌다" },
  { kanji: "不味い", hiragana: "まずい", meaning: "맛이 없다" },
  { kanji: "七日", hiragana: "なのか", meaning: "7일, 이레" },
  { kanji: "冬", hiragana: "ふゆ", meaning: "겨울" },
  { kanji: "兄弟", hiragana: "きょうだい", meaning: "형제" },
  { kanji: "あちら", hiragana: "", meaning: "저쪽, 저기" },
  { kanji: "困る", hiragana: "こまる", meaning: "곤란하다" },
  { kanji: "ストーブ", hiragana: "", meaning: "난로, 스토브" },
  { kanji: "横", hiragana: "よこ", meaning: "옆, 가로" },
  { kanji: "新しい", hiragana: "あたらしい", meaning: "새롭다" },
  { kanji: "ノート", hiragana: "", meaning: "노트" },
  { kanji: "夏休み", hiragana: "なつやすみ", meaning: "여름방학, 여름휴가" },
  { kanji: "食べ物", hiragana: "たべもの", meaning: "먹을 것, 음식" },
  { kanji: "どういたしまして", hiragana: "", meaning: "천만에요, 별 말씀을요" },
  { kanji: "階段", hiragana: "かいだん", meaning: "계단" },
  { kanji: "結婚", hiragana: "けっこん", meaning: "결혼" },
  { kanji: "葉書", hiragana: "はがき", meaning: "엽서" },
  { kanji: "食堂", hiragana: "しょくどう", meaning: "식당" },
  { kanji: "長い", hiragana: "ながい", meaning: "길다" },
  { kanji: "スカート", hiragana: "", meaning: "스커트, 치마" },
  { kanji: "ボールペン", hiragana: "", meaning: "볼펜" },
  { kanji: "弱い", hiragana: "よわい", meaning: "약하다" },
  { kanji: "去年", hiragana: "きょねん", meaning: "지난해, 작년" },
  { kanji: "被る", hiragana: "かぶる", meaning: "쓰다, 뒤집어쓰다, 겹치다" },
  { kanji: "私", hiragana: "わたし", meaning: "나, 저" },
  { kanji: "出す", hiragana: "だす", meaning: "내다, 내놓다, 꺼내다" },
];
